'use strict';

// Deutlich frecher 18+-Pool. Die Aufgaben bleiben freiwillig: keine Karte
// verlangt Nacktheit, intime Berührungen oder das Offenlegen privater Inhalte.
module.exports = {
  nie: [
    'Ich hab noch nie einer Person geschrieben: „Bist du noch wach?“ – und genau gewusst, worauf ich hinauswill.',
    'Ich hab noch nie eine anzügliche Nachricht an die falsche Person geschickt.',
    'Ich hab noch nie Sexting betrieben.',
    'Ich hab noch nie ein Nacktbild verschickt.',
    'Ich hab noch nie ein Nacktbild bekommen, mit dem ich nicht gerechnet hatte.',
    'Ich hab noch nie einen One-Night-Stand gehabt.',
    'Ich hab noch nie eine Freundschaft-plus-Situation gehabt.',
    'Ich hab noch nie jemanden aus meinem Freundeskreis geküsst.',
    'Ich hab noch nie mit jemandem aus dieser Runde geflirtet.',
    'Ich hab noch nie von jemandem aus dieser Runde etwas Versautes geträumt.',
    'Ich hab noch nie jemanden nur wegen seiner Stimme attraktiv gefunden.',
    'Ich hab noch nie jemanden nur wegen seines Geruchs attraktiv gefunden.',
    'Ich hab noch nie beim ersten Date geknutscht.',
    'Ich hab noch nie beim ersten Date mehr als nur geknutscht.',
    'Ich hab noch nie zwei Personen gleichzeitig gedatet.',
    'Ich hab noch nie nach einem Kuss sofort meine Freunde informiert.',
    'Ich hab noch nie einen Knutschfleck verstecken müssen.',
    'Ich hab noch nie an einem ungewöhnlichen Ort Sex gehabt.',
    'Ich hab noch nie Sex im Auto gehabt.',
    'Ich hab noch nie Sex im Freien gehabt.',
    'Ich hab noch nie beinahe beim Sex erwischt worden.',
    'Ich hab noch nie während eines Dates so getan, als müsste ich früh raus, weil die Chemie nicht gestimmt hat.',
    'Ich hab noch nie nach einem Date den Chat gemeinsam mit Freunden analysiert.',
    'Ich hab noch nie eine Dating-App nur für einen Abend neu installiert.',
    'Ich hab noch nie ein Dating-App-Match wegen eines einzigen Satzes sofort gelöscht.',
    'Ich hab noch nie mein Alter auf einer Dating-App geschönt.',
    'Ich hab noch nie mein Datingprofil absichtlich heißer dargestellt, als mein Alltag wirklich ist.',
    'Ich hab noch nie jemanden über Social Media angeschrieben, weil ich die Person heiß fand.',
    'Ich hab noch nie beim Stalken versehentlich ein sehr altes Bild geliked.',
    'Ich hab noch nie einen Screenshot von einem heißen Chat an Freunde geschickt.',
    'Ich hab noch nie eine zweideutige Sprachnachricht aufgenommen und dann doch gelöscht.',
    'Ich hab noch nie ein anzügliches Emoji benutzt und danach behauptet, es sei nicht so gemeint gewesen.',
    'Ich hab noch nie einen Kuss bereut, bevor er überhaupt vorbei war.',
    'Ich hab noch nie jemanden geküsst, dessen Nachnamen ich nicht kannte.',
    'Ich hab noch nie jemanden geküsst, um eine andere Person eifersüchtig zu machen.',
    'Ich hab noch nie mit einem Ex noch einmal etwas angefangen.',
    'Ich hab noch nie nach einer Trennung noch einmal mit der Person geschlafen.',
    'Ich hab noch nie Gefühle bei einer eigentlich lockeren Sache entwickelt.',
    'Ich hab noch nie so getan, als hätte ich keine Gefühle, obwohl ich längst welche hatte.',
    'Ich hab noch nie einen Orgasmus vorgetäuscht.',
    'Ich hab noch nie beim Sex lachen müssen.',
    'Ich hab noch nie beim Sex an jemand anderen gedacht.',
    'Ich hab noch nie einen Namen im falschen Moment verwechselt.',
    'Ich hab noch nie ein Sexspielzeug gekauft.',
    'Ich hab noch nie ein Sexspielzeug geschenkt bekommen.',
    'Ich hab noch nie Rollenspiele ausprobiert.',
    'Ich hab noch nie Handschellen oder eine Augenbinde im Schlafzimmer benutzt.',
    'Ich hab noch nie einen Porno zusammen mit einer anderen Person geschaut.',
    'Ich hab noch nie auf einer Pornoseite länger nach dem passenden Video gesucht als das Video später lief.',
    'Ich hab noch nie meinen Browserverlauf wegen etwas Versautem gelöscht.',
    'Ich hab noch nie vergessen, einen privaten Tab zu schließen.',
    'Ich hab noch nie bei einem Film so getan, als wäre eine Sexszene überhaupt nicht unangenehm.',
    'Ich hab noch nie eine berühmte Person gegoogelt und dabei bewusst „nackt“ ergänzt.',
    'Ich hab noch nie einen erotischen Traum von einer völlig unerwarteten Person gehabt.',
    'Ich hab noch nie einen Fetisch interessant gefunden, den ich früher komisch fand.',
    'Ich hab noch nie eine geheime Fantasie gehabt, die niemand hier erraten würde.',
    'Ich hab noch nie einen Anmachspruch benutzt, den ich vorher im Internet gesucht hatte.',
    'Ich hab noch nie nur wegen eines heißen Fotos auf eine Story reagiert.',
    'Ich hab noch nie morgens neben jemandem gelegen und kurz überlegen müssen, was am Abend passiert ist.',
    'Ich hab noch nie behauptet, ich wolle „nur kuscheln“, obwohl ich auf mehr gehofft habe.'
  ],

  wahl: [
    'Wer würde am ehesten betrunken dem Ex „Bist du wach?“ schreiben?',
    'Wer würde am ehesten heute noch mit jemandem knutschen?',
    'Wer würde am ehesten einen One-Night-Stand haben?',
    'Wer würde am ehesten aus einem One-Night-Stand eine Beziehung machen?',
    'Wer würde am ehesten bei einer Freundschaft plus Gefühle entwickeln?',
    'Wer würde am ehesten jemanden aus dieser Runde daten?',
    'Wer würde am ehesten heimlich auf jemanden aus dieser Runde stehen?',
    'Wer würde am ehesten bei einem Date zuerst küssen?',
    'Wer würde am ehesten schon beim ersten Date mit nach Hause gehen?',
    'Wer würde am ehesten einen völlig Fremden erfolgreich ansprechen?',
    'Wer würde am ehesten mit einem richtig schlechten Anmachspruch trotzdem Erfolg haben?',
    'Wer würde am ehesten beim Flirten komplett die Nerven verlieren?',
    'Wer würde am ehesten einen Flirt falsch verstehen und schon die Hochzeit planen?',
    'Wer würde am ehesten nur wegen einer heißen Stimme schwach werden?',
    'Wer würde am ehesten sich in einen Barkeeper oder eine Barkeeperin vergucken?',
    'Wer würde am ehesten auf einer Hochzeit mit jemandem verschwinden?',
    'Wer würde am ehesten einen Urlaubsflirt anfangen?',
    'Wer würde am ehesten einen Urlaubsflirt auch zuhause weiterführen?',
    'Wer würde am ehesten einen Ex zurücknehmen, obwohl alle abraten?',
    'Wer würde am ehesten noch einmal mit einem Ex im Bett landen?',
    'Wer würde am ehesten mehrere Dating-Apps gleichzeitig nutzen?',
    'Wer würde am ehesten die frechste Dating-Bio haben?',
    'Wer würde am ehesten beim Swipen die höchsten Ansprüche haben?',
    'Wer würde am ehesten ein Match nach drei Nachrichten direkt treffen?',
    'Wer würde am ehesten ein Date unter einem Vorwand vorzeitig verlassen?',
    'Wer würde am ehesten nach einem Date jede Nachricht der Gruppe zur Analyse schicken?',
    'Wer würde am ehesten einen Screenshot vom Sexting-Chat an die beste Freundin oder den besten Freund schicken?',
    'Wer würde am ehesten ein anzügliches Bild verschicken?',
    'Wer würde am ehesten ein anzügliches Bild an die falsche Person schicken?',
    'Wer würde am ehesten den versautesten Suchverlauf haben?',
    'Wer würde am ehesten den Privatmodus am häufigsten benutzen?',
    'Wer würde am ehesten auf Pornhub sofort die passende Kategorie kennen?',
    'Wer würde am ehesten ein OnlyFans-Abo geheim halten?',
    'Wer würde am ehesten ein eigenes OnlyFans erfolgreich vermarkten?',
    'Wer würde am ehesten das größte Sexspielzeug besitzen?',
    'Wer würde am ehesten ein Sexspielzeug als Geburtstagsgeschenk verschenken?',
    'Wer würde am ehesten im Schlafzimmer etwas völlig Neues vorschlagen?',
    'Wer würde am ehesten eine ungewöhnliche Fantasie offen ansprechen?',
    'Wer würde am ehesten Rollenspiele ernsthaft gut spielen?',
    'Wer würde am ehesten beim Sex einen Lachanfall bekommen?',
    'Wer würde am ehesten beim Küssen die beste Bewertung bekommen?',
    'Wer würde am ehesten den besten Striptease hinlegen?',
    'Wer würde am ehesten bei einem sexy Fotoshooting am selbstbewusstesten sein?',
    'Wer würde am ehesten nackt schlafen?',
    'Wer würde am ehesten morgens direkt wieder Lust haben?',
    'Wer würde am ehesten eine Nacht lang nur kuscheln wirklich durchhalten?',
    'Wer würde am ehesten beim Dirty Talk überraschend kreativ sein?',
    'Wer würde am ehesten beim Dirty Talk lachen müssen?',
    'Wer würde am ehesten einen Knutschfleck an einer unmöglichen Stelle verstecken müssen?',
    'Wer würde am ehesten im Auto erwischt werden?',
    'Wer würde am ehesten Sex an einem öffentlichen Ort ausprobieren?',
    'Wer würde am ehesten beim Sex die Nachbarn stören?',
    'Wer würde am ehesten ein Safeword vergessen, weil es zu absurd ist?',
    'Wer würde am ehesten eine Sexszene in einem Film laut kommentieren?',
    'Wer würde am ehesten bei einer zweideutigen Frage sofort rot werden?',
    'Wer würde am ehesten behaupten, total unschuldig zu sein, obwohl niemand das glaubt?',
    'Wer würde am ehesten die meisten Menschen in dieser Runde schon einmal attraktiv gefunden haben?',
    'Wer würde am ehesten nach zwei Drinks viel offensiver flirten?',
    'Wer würde am ehesten heute noch eine Nummer bekommen?',
    'Wer würde am ehesten morgen eine sehr interessante Geschichte erzählen müssen?'
  ],

  wahrheit: [
    'Was ist deine größte Red Flag im Bett?',
    'Was ist dein größter Abturner beim Küssen?',
    'Was macht jemanden für dich sofort heiß?',
    'Welches Körperteil findest du bei anderen am attraktivsten?',
    'Welches Körperteil an dir selbst findest du am attraktivsten?',
    'Was war dein bester Kuss und warum?',
    'Was war dein schlimmster Kuss und warum?',
    'Mit wem aus dieser Runde würdest du am ehesten knutschen?',
    'Mit wem aus dieser Runde würdest du am ehesten auf ein Date gehen?',
    'Wer aus dieser Runde wäre vermutlich am besten im Bett?',
    'Wer aus dieser Runde hat die größte Dirty-Mind-Energie?',
    'Welche Person hier könnte dich mit einem einzigen Blick nervös machen?',
    'Hattest du schon einmal einen erotischen Traum von jemandem, den du regelmäßig siehst?',
    'Was war die unerwartetste Person, von der du je etwas Versautes geträumt hast?',
    'Was ist die harmloseste Sache, die dich überraschend anmacht?',
    'Welche Fantasie würdest du gern einmal ausprobieren?',
    'Welche Fantasie würdest du niemals ausprobieren?',
    'Gibt es einen Fetisch, den du interessanter findest, als du zugeben möchtest?',
    'Was war dein ungewöhnlichster Ort für Sex oder Knutschen?',
    'Wo würdest du es gern einmal tun, wenn ihr garantiert ungestört wärt?',
    'Was war dein peinlichster Moment beim Sex?',
    'Was war der lustigste Satz, der dir beim Sex herausgerutscht ist?',
    'Hast du schon einmal einen Orgasmus vorgetäuscht – und warum?',
    'Was ist wichtiger: gutes Küssen oder guter Sex?',
    'Wie lange war dein längster One-Night-Stand am nächsten Morgen noch da?',
    'Würdest du lieber eine Freundschaft plus oder einen One-Night-Stand haben?',
    'Hast du dich schon einmal in eine eigentlich lockere Sache verliebt?',
    'Würdest du noch einmal mit einem Ex schlafen?',
    'Welche Nachricht an einen Ex würdest du heute am meisten bereuen?',
    'Was ist der frechste Satz, den du je beim Flirten geschrieben hast?',
    'Was ist die zweideutigste Nachricht, die du zuletzt bekommen hast?',
    'Welche drei Emojis beschreiben dein Sexleben am besten?',
    'Wie würde der Titel eines Films über dein Sexleben heißen?',
    'Welchen Künstlernamen würdest du dir als Pornostar geben?',
    'Welche Pornoseite würdest du am schnellsten am Logo erkennen?',
    'Welche Pornokategorie würdest du niemals im Verlauf stehen lassen?',
    'Hast du schon einmal für erotischen Content bezahlt?',
    'Würdest du für eine Million Euro erotischen Content von dir veröffentlichen?',
    'Was ist das gewagteste Bild, das du je verschickt hast?',
    'Hast du schon einmal nach dem Verschicken eines intimen Bildes sofort Panik bekommen?',
    'Was ist dein ehrlichstes Urteil über Dirty Talk?',
    'Welches Wort klingt für dich beim Dirty Talk sofort lächerlich?',
    'Bist du im Schlafzimmer eher dominant, eher zurückhaltend oder irgendwo dazwischen?',
    'Licht an, Licht aus oder völlig egal?',
    'Morgens, tagsüber oder nachts – wann ist für dich die beste Zeit?',
    'Was würdest du lieber nie wieder erleben: schlechten Sex oder einen richtig schlechten Kuss?',
    'Wie wichtig ist Humor beim Sex?',
    'Was ist eine Sache, die ein Partner oder eine Partnerin unbedingt vorher fragen sollte?',
    'Was ist deine beste Regel für guten, einvernehmlichen Sex?',
    'Welche versaut klingende Behauptung über dich würde die Runde wahrscheinlich sofort glauben?'
  ],

  pflicht: [
    'Erfinde deinen Pornostar-Namen aus deinem zweiten Vornamen und einer Snackmarke.',
    'Gib dem heutigen Abend einen völlig übertriebenen Pornofilmtitel.',
    'Erfinde einen zweideutigen Filmtitel mit den Namen von zwei Spielern.',
    'Lies den Satz „Die Spülmaschine ist fertig“ so verführerisch wie möglich vor.',
    'Mach zehn Sekunden lang einen Striptease-Move – alle Kleidungsstücke bleiben an.',
    'Zeig der Runde dein bestes Flirtgesicht.',
    'Spiele 15 Sekunden lang einen übertrieben sexy Werbespot für dein Getränk.',
    'Verkaufe einen völlig normalen Haushaltsgegenstand wie ein sündhaftes Spielzeug.',
    'Flüstere einen absurden Anmachspruch in Richtung Kamera oder Zimmerdecke.',
    'Erfinde den schlechtesten Dirty-Talk-Satz der Welt.',
    'Sag drei Gemüsesorten so verführerisch wie möglich.',
    'Stöhne den Namen eines Haushaltsgeräts dramatisch.',
    'Imitiere fünf Sekunden lang den Anfang eines schlechten Erwachsenenfilms – ohne jemanden anzufassen.',
    'Mach eine Wettervorhersage für eine angeblich sehr heiße Nacht.',
    'Beschreibe deine Lieblingsstellung als Sportkommentar, ohne ihren Namen zu nennen.',
    'Erkläre Küssen wie ein völlig überforderter Fahrlehrer.',
    'Erfinde ein Safeword, das garantiert jede Stimmung ruiniert.',
    'Nenne fünf Begriffe, die harmlos sind, aber versaut klingen.',
    'Formuliere eine Dating-Bio, die gleichzeitig heiß und maximal peinlich ist.',
    'Mach der Person gegenüber ein zweideutiges, aber respektvolles Kompliment.',
    'Lass die Gruppe dir einen anzüglichen Künstlernamen geben, den du zwei Runden lang trägst.',
    'Spiele vor, wie du in Zeitlupe jemanden in einer Bar ansprichst.',
    'Imitiere einen schlechten Verführer aus einer Telenovela.',
    'Lies die letzten fünf von dir benutzten Emojis wie eine erotische Geschichte vor.',
    'Erfinde einen Werbeslogan für Kondome, der niemals genehmigt würde.',
    'Mach 15 Sekunden lang eine Hotline-Stimme für völlig unsexy Alltagsprobleme.',
    'Erkläre der Runde mit ernster Stimme, warum Socken angeblich sexy sind.',
    'Singe einen bekannten Refrain so, als wäre er eindeutig zweideutig.',
    'Mach eine dramatische Dankesrede an dein Bett.',
    'Erfinde einen Cocktailnamen, der nicht jugendfrei klingt.',
    'Stelle pantomimisch einen schlechten Kuss dar – ohne eine andere Person zu berühren.',
    'Zeig drei verschiedene Arten, wie man beim Flirten Blickkontakt komplett falsch macht.',
    'Erfinde eine erotische Kurzgeschichte in genau fünf harmlosen Wörtern.',
    'Sag das Alphabet so, als würdest du in einem schlechten Erotik-Hörbuch sprechen.',
    'Nenne jeder Person in der Runde einen charmanten Dating-App-Spitznamen.',
    'Mach eine zehnsekündige Pole-Dance-Choreografie an einem unsichtbaren Pfosten.',
    'Erfinde eine versaute Bedeutung für die Abkürzung SüffIQ.',
    'Beschreibe einen Döner so leidenschaftlich, dass es unangenehm wird.',
    'Spiele einen eifersüchtigen Liebhaber in einer völlig übertriebenen Seifenoper.',
    'Gib eine Pressekonferenz zu deinem angeblich skandalösen Liebesleben.',
    'Erfinde drei respektvolle Regeln für ein völlig chaotisches erstes Date.',
    'Sag einen Satz, der im Schlafzimmer und beim Möbelaufbau funktioniert.',
    'Sag einen Satz, der beim Sex und beim Einparken funktioniert.',
    'Sag einen Satz, der beim Küssen und beim Döneressen funktioniert.',
    'Mach den Soundeffekt für eine romantische Szene, die sofort schiefgeht.'
  ],

  oder: [
    ['Nie wieder küssen', 'Nie wieder Sex'],
    ['Nur noch schlechter Sex', 'Nur noch schlechte Küsse'],
    ['One-Night-Stand', 'Freundschaft plus'],
    ['Sex am Morgen', 'Sex mitten in der Nacht'],
    ['Licht komplett an', 'Licht komplett aus'],
    ['Dirty Talk', 'Komplett still'],
    ['Dominant sein', 'Die Führung abgeben'],
    ['Spontan und wild', 'Lang geplant und romantisch'],
    ['Nur küssen und nie mehr', 'Alles außer küssen'],
    ['Im Auto', 'Im Freien'],
    ['Erwischt werden', 'Den falschen Namen sagen'],
    ['Sexting', 'Anzügliche Sprachnachrichten'],
    ['Ein Nacktbild verschicken', 'Eine versaute Nachricht vorlesen'],
    ['Deinen Suchverlauf zeigen', 'Deine Dating-App-Chats zeigen'],
    ['Nie wieder Pornos', 'Nie wieder Sexspielzeug'],
    ['Gemeinsam Pornos schauen', 'Gemeinsam erotische Geschichten lesen'],
    ['Knutschfleck am Hals', 'Kratzspuren am Rücken'],
    ['Zu laut sein', 'Beim Sex lachen müssen'],
    ['Ein sehr langes Vorspiel', 'Direkt zur Sache kommen'],
    ['Hotelzimmer', 'Zelt auf einem Festival'],
    ['Mit einem Ex', 'Mit dem Crush der besten Freundin oder des besten Freundes'],
    ['Erstes Date bei dir', 'Erstes Date bei der anderen Person'],
    ['Perfektes Aussehen', 'Perfekte Chemie'],
    ['Jemand, der fantastisch küsst', 'Jemand, der fantastisch flirtet'],
    ['Eine geheime Fantasie erzählen', 'Eine peinliche Erfahrung erzählen'],
    ['Dein Pornostar-Name wird öffentlich', 'Deine letzte anzügliche Nachricht wird öffentlich'],
    ['Ein Jahr ohne Dating', 'Ein Jahr ohne Sex'],
    ['Nur noch romantischer Sex', 'Nur noch spontaner Sex'],
    ['Immer den ersten Schritt machen', 'Nie den ersten Schritt machen dürfen'],
    ['Eine Nacht mit dem Promi-Crush', 'Ein Jahr mit dem echten Crush'],
    ['Sehr guter Sex ohne Beziehung', 'Mittelmäßiger Sex in der Traumbeziehung'],
    ['Alle Fantasien des Partners kennen', 'Der Partner kennt alle deine Fantasien'],
    ['Beim Küssen die Augen immer offen', 'Beim Sex immer Socken tragen'],
    ['Nie wieder Dirty Talk', 'Nur noch in Reimen Dirty Talk'],
    ['Dein Ex bewertet deine Küsse', 'Dein bester Freund bewertet deine Dating-Bio']
  ],

  mehrheit: [
    { q: 'Was macht jemanden am schnellsten attraktiv?', o: ['Humor', 'Stimme', 'Blicke', 'Körper'] },
    { q: 'Was ist beim Küssen am wichtigsten?', o: ['Timing', 'Technik', 'Chemie', 'Mut'] },
    { q: 'Was ist der größte Abturner beim Date?', o: ['Arroganz', 'Handy', 'Schlechter Atem', 'Ex-Geschichten'] },
    { q: 'Wo beginnt für euch Fremdgehen?', o: ['Flirten', 'Sexting', 'Küssen', 'Erst beim Sex'] },
    { q: 'Was ist heißer?', o: ['Gute Stimme', 'Guter Duft', 'Guter Stil', 'Gute Hände'] },
    { q: 'Was funktioniert beim Flirten am besten?', o: ['Humor', 'Direktheit', 'Blickkontakt', 'Komplimente'] },
    { q: 'Welche Dating-App-Energie ist am gefährlichsten?', o: ['Tinder', 'Bumble', 'Instagram-DM', 'Nachts um drei'] },
    { q: 'Was ist peinlicher?', o: ['Schlechter Kuss', 'Falscher Name', 'Lachflash', 'Erwischt werden'] },
    { q: 'Was gehört am ehesten ins Schlafzimmer?', o: ['Musik', 'Kerzen', 'Spiegel', 'Gar nichts davon'] },
    { q: 'Welche Zeit ist für Sex am besten?', o: ['Morgens', 'Nachmittags', 'Abends', 'Nachts'] },
    { q: 'Was zählt mehr?', o: ['Vorspiel', 'Ausdauer', 'Kreativität', 'Kommunikation'] },
    { q: 'Was ist bei einer lockeren Sache am schwierigsten?', o: ['Keine Gefühle', 'Eifersucht', 'Kommunikation', 'Das Ende'] },
    { q: 'Welche Nachricht ist am eindeutigsten?', o: ['Bist du wach?', 'Kommst du noch?', 'Was machst du?', 'Nur ein Emoji'] },
    { q: 'Was verrät am meisten über jemanden?', o: ['Suchverlauf', 'Dating-Chats', 'Fotos', 'Notizen-App'] },
    { q: 'Was ist das beste Kompliment?', o: ['Du bist heiß', 'Du riechst gut', 'Du küsst gut', 'Ich fühle mich wohl'] },
    { q: 'Was wäre als Safeword am schlimmsten?', o: ['Mama', 'Steuererklärung', 'Brokkoli', 'Windows-Update'] },
    { q: 'Welche Situation wird am schnellsten zweideutig?', o: ['Kochen', 'Massage', 'Tanzen', 'Filmabend'] },
    { q: 'Was ist am wichtigsten für guten Sex?', o: ['Vertrauen', 'Chemie', 'Erfahrung', 'Humor'] },
    { q: 'Welche Art von Kuss gewinnt?', o: ['Langsam', 'Wild', 'Überraschend', 'Mit viel Blickkontakt'] },
    { q: 'Was macht Dirty Talk gut?', o: ['Stimme', 'Wortwahl', 'Selbstbewusstsein', 'Timing'] },
    { q: 'Was ist beim One-Night-Stand am wichtigsten?', o: ['Anziehung', 'Respekt', 'Diskretion', 'Frühstück'] },
    { q: 'Welcher Ort klingt am heißesten?', o: ['Hotel', 'Auto', 'Dusche', 'Küche'] },
    { q: 'Was wäre schlimmer, wenn die Gruppe es sieht?', o: ['Pornosuchverlauf', 'Sexting', 'Nacktbilder', 'Datingprofil'] },
    { q: 'Wer sollte beim Date den ersten Schritt machen?', o: ['Immer ich', 'Immer die andere Person', 'Wer mutiger ist', 'Völlig egal'] },
    { q: 'Was ist die größte Schlafzimmer-Red-Flag?', o: ['Kein Fragen', 'Nur Ego', 'Kein Humor', 'Ex-Vergleiche'] },
    { q: 'Was ist die beste Reaktion auf einen schlechten Anmachspruch?', o: ['Mitspielen', 'Kontern', 'Ignorieren', 'Noch schlechteren bringen'] },
    { q: 'Was klingt unschuldig, endet aber selten unschuldig?', o: ['Film schauen', 'Massage', 'Ein letzter Drink', 'Nur kurz hochkommen'] },
    { q: 'Welche Eigenschaft macht am ehesten guten Sex aus?', o: ['Aufmerksamkeit', 'Selbstbewusstsein', 'Ausdauer', 'Spontanität'] },
    { q: 'Was ist nach einer heißen Nacht am besten?', o: ['Kuscheln', 'Schlafen', 'Frühstück', 'Direkt wiederholen'] },
    { q: 'Welche 18+-Runde eskaliert am schnellsten?', o: ['Ich hab noch nie', 'Wahrheit', 'Wer würde eher', 'Entweder oder'] }
  ],

  skala: [
    'Wie versaut ist dein Humor? 1 = Kirchenchor, 10 = jeder Satz wird zweideutig.',
    'Wie gefährlich ist dein Suchverlauf? 1 = Kochrezepte, 10 = sofort Handy verbrennen.',
    'Wie gut kannst du flirten? 1 = Wetter-App, 10 = Nummer in zwei Minuten.',
    'Wie gut küsst du deiner eigenen Meinung nach? 1 = Unfall, 10 = Wiederholungsgefahr.',
    'Wie schnell würdest du heute jemanden küssen? 1 = niemals, 10 = wen genau?',
    'Wie wahrscheinlich würdest du einen One-Night-Stand haben? 1 = ausgeschlossen, 10 = Tasche ist gepackt.',
    'Wie offen redest du über Sex? 1 = gar nicht, 10 = viel zu detailliert.',
    'Wie wichtig ist dir Dirty Talk? 1 = bitte schweigen, 10 = eigenes Drehbuch.',
    'Wie eifersüchtig bist du? 1 = völlig entspannt, 10 = FBI-Modus.',
    'Wie dominant bist du im Schlafzimmer? 1 = entscheide du, 10 = ich gebe die Ansagen.',
    'Wie spontan bist du im Bett? 1 = Kalendertermin, 10 = jederzeit und überall.',
    'Wie wichtig ist gutes Küssen? 1 = Nebensache, 10 = Ausschlusskriterium.',
    'Wie groß ist dein Interesse an Sexspielzeug? 1 = gar keines, 10 = Warenkorb voll.',
    'Wie wahrscheinlich würdest du Sexting anfangen? 1 = niemals, 10 = Nachricht ist getippt.',
    'Wie mutig bist du beim Verschicken anzüglicher Bilder? 1 = niemals, 10 = beste Beleuchtung steht.',
    'Wie schlimm wäre es, wenn die Runde deinen Privatmodus-Verlauf sieht? 1 = langweilig, 10 = neues Leben anfangen.',
    'Wie sehr stehst du auf Rollenspiele? 1 = nein, 10 = Kostüm liegt bereit.',
    'Wie wichtig ist Humor beim Sex? 1 = ernst bleiben, 10 = Lachflash gehört dazu.',
    'Wie wahrscheinlich würdest du noch einmal mit einem Ex schlafen? 1 = niemals, 10 = Nummer schon offen.',
    'Wie wahrscheinlich entwickelst du bei einer Freundschaft plus Gefühle? 1 = ausgeschlossen, 10 = nach dem ersten Treffen.',
    'Wie gut kannst du einen Knutschfleck verstecken? 1 = unmöglich, 10 = Profi-Make-up.',
    'Wie laut bist du vermutlich im Bett? 1 = lautlos, 10 = Nachbarschaft kennt den Namen.',
    'Wie wichtig ist dir ein Frühstück danach? 1 = direkt weg, 10 = Brunch reserviert.',
    'Wie gut kannst du über Grenzen und Wünsche reden? 1 = sehr schwer, 10 = klar und direkt.',
    'Wie wahrscheinlich würdest du erotischen Content von dir verkaufen? 1 = nie, 10 = Preis steht fest.',
    'Wie heiß findest du Tattoos? 1 = egal, 10 = sofort schwach.',
    'Wie heiß findest du Uniformen? 1 = gar nicht, 10 = gefährlich.',
    'Wie schnell wirst du bei versauten Fragen rot? 1 = nie, 10 = schon passiert.',
    'Wie viel Erfahrung behauptest du zu haben? 1 = ehrlich bescheiden, 10 = Legende im eigenen Kopf.',
    'Wie wahrscheinlich produziert diese Runde heute noch eine nicht jugendfreie Story? 1 = brave Nacht, 10 = morgen Erklärungsbedarf.'
  ]
};
