'use strict';

module.exports = {
  nie: [
    'Ich hab noch nie jemanden geküsst und es direkt danach bereut.',
    'Ich hab noch nie mit jemandem geflirtet, obwohl ich wusste, dass daraus nichts wird.',
    'Ich hab noch nie eine Nachricht geschrieben und sie fünfmal gelöscht, weil sie zu eindeutig war.',
    'Ich hab noch nie jemanden aus dieser Runde heimlich attraktiv gefunden.',
    'Ich hab noch nie beim ersten Date gelogen, um interessanter zu wirken.',
    'Ich hab noch nie einen Kater verschwiegen und so getan, als wäre ich einfach nur müde.',
    'Ich hab noch nie betrunken eine Person angeschrieben, die ich nüchtern niemals angeschrieben hätte.',
    'Ich hab noch nie einen Kuss nur wegen einer Wette zugelassen.',
    'Ich hab noch nie jemanden absichtlich eifersüchtig gemacht.',
    'Ich hab noch nie einen peinlichen Flirt-Screenshot an Freunde geschickt.',
    'Ich hab noch nie beim Feiern meine eigene Grenze komplett falsch eingeschätzt.',
    'Ich hab noch nie mit jemandem rumgemacht, dessen Nachnamen ich nicht kannte.',
    'Ich hab noch nie behauptet, mich an einen Abend nicht zu erinnern, obwohl ich mich sehr wohl erinnert habe.',
    'Ich hab noch nie eine Dating-App nur aus Langeweile geöffnet.',
    'Ich hab noch nie jemanden geghostet.',
    'Ich hab noch nie nach einem Date sofort die Freunde angerufen und alles bewertet.',
    'Ich hab noch nie einen Crush auf jemanden gehabt, der absolut keine gute Idee war.',
    'Ich hab noch nie einen Flirt begonnen, nur um ein kostenloses Getränk zu bekommen.',
    'Ich hab noch nie jemanden geküsst, obwohl ein Freund oder eine Freundin mir vorher davon abgeraten hat.',
    'Ich hab noch nie eine zweideutige Nachricht absichtlich so formuliert, dass ich sie im Notfall harmlos erklären kann.',
    'Ich hab noch nie in einer Beziehung heimlich alte Chats mit einem Ex gelesen.',
    'Ich hab noch nie auf einer Party länger mit jemandem geredet, nur weil ich die Person heiß fand.',
    'Ich hab noch nie versucht herauszufinden, wer mich auf Social Media entfolgt hat.',
    'Ich hab noch nie eine Story hauptsächlich für eine bestimmte Person gepostet.'
  ],

  wahl: [
    'Wer würde am ehesten heute noch mit einer Person aus dieser Runde flirten?',
    'Wer würde am ehesten nach drei Drinks seinem Ex schreiben?',
    'Wer würde am ehesten einen One-Night-Stand am nächsten Morgen zuerst vergessen wollen?',
    'Wer würde am ehesten beim Flirten komplett überschätzen, wie gut es gerade läuft?',
    'Wer würde am ehesten aus Versehen eine sehr private Nachricht in die falsche Gruppe schicken?',
    'Wer würde am ehesten einen Crush monatelang geheim halten?',
    'Wer würde am ehesten beim ersten Date zu viel erzählen?',
    'Wer würde am ehesten einen Kuss anfangen und danach behaupten, die andere Person habe angefangen?',
    'Wer würde am ehesten auf einer Hochzeit mit jemandem Fremden verschwinden?',
    'Wer würde am ehesten einen peinlichen Spitznamen nach einer Partynacht bekommen?',
    'Wer würde am ehesten beim Dating zuerst die Freunde der Person stalken?',
    'Wer würde am ehesten einen Flirt mit einem richtig schlechten Spruch starten?',
    'Wer würde am ehesten aus Eifersucht etwas komplett Unnötiges machen?',
    'Wer würde am ehesten eine Dating-App nach zehn Minuten wieder löschen und am nächsten Tag neu installieren?',
    'Wer würde am ehesten einen Urlaubsflirt zu ernst nehmen?',
    'Wer würde am ehesten beim Strip-Poker zuerst verlieren?',
    'Wer würde am ehesten behaupten, niemals eifersüchtig zu sein, und wäre es am Ende am meisten?',
    'Wer würde am ehesten nach einer wilden Nacht am nächsten Morgen alle Details rekonstruieren müssen?'
  ],

  wahrheit: [
    'Wer aus dieser Runde wäre am ehesten dein Typ – rein optisch?',
    'Was war dein schlechtester Flirtversuch?',
    'Was ist die peinlichste Nachricht, die du jemals betrunken verschickt hast?',
    'Was ist für dich ein sofortiger Abturner beim Dating?',
    'Welche Person solltest du wirklich nicht mehr anschreiben, würdest es aber wahrscheinlich trotzdem tun?',
    'Was war dein unangenehmster Kuss?',
    'Hast du schon einmal Interesse vorgespielt, obwohl du eigentlich nur Aufmerksamkeit wolltest?',
    'Was ist das Dümmste, das du aus Eifersucht gemacht hast?',
    'Welche Eigenschaft macht jemanden für dich sofort attraktiv?',
    'Was war deine größte Red Flag, die du trotzdem ignoriert hast?',
    'Was war dein schnellster Sinneswandel nach einem Date?',
    'Mit welcher berühmten Person würdest du ohne lang nachzudenken auf ein Date gehen?',
    'Was ist etwas, das du beim Flirten niemals zugeben würdest, obwohl es stimmt?',
    'Welcher Chat auf deinem Handy wäre dir gerade am unangenehmsten, wenn ihn alle sehen würden?',
    'Was war das Lächerlichste, das du getan hast, um jemanden zu beeindrucken?',
    'Hast du schon einmal jemanden absichtlich warten lassen, um cooler zu wirken?',
    'Welche Person aus deiner Vergangenheit würdest du aus reiner Neugier gern noch einmal treffen?',
    'Was ist dein toxischster Dating-Move?',
    'Wie schnell merkst du normalerweise, dass du jemanden wirklich magst?',
    'Was ist das Mutigste, das du je beim Flirten gemacht hast?'
  ],

  pflicht: [
    'Mach der Person links von dir ein völlig übertriebenes Kompliment, als würdest du sie gerade in einer Dating-Show kennenlernen.',
    'Lies deinen letzten harmlosen Chat-Satz mit maximal verführerischer Stimme vor.',
    'Erfinde für die Person rechts von dir einen absurden Dating-Profil-Slogan.',
    'Zeige 15 Sekunden lang deinen besten Blick für ein Dating-Profilfoto.',
    'Flirte 20 Sekunden lang mit einer Wasserflasche oder deinem Getränk.',
    'Erfinde einen richtig schlechten Anmachspruch und trage ihn mit voller Überzeugung vor.',
    'Spiele 15 Sekunden lang eine extrem dramatische Trennungsszene.',
    'Lass die Gruppe dir einen Dating-App-Bio-Satz diktieren – du musst ihn nur laut vorlesen, nicht posten.',
    'Bewerte deinen eigenen Flirt-Skill von 1 bis 10 und verteidige die Zahl zehn Sekunden lang.',
    'Imitiere, wie du glaubst, dass du nach vier Drinks flirtest.',
    'Mach einen Heiratsantrag an einen völlig ungeeigneten Gegenstand im Raum.',
    'Erkläre der Gruppe in 20 Sekunden, warum du angeblich der perfekte Urlaubsflirt wärst.',
    'Spiele eine peinlich selbstbewusste Dating-Show-Vorstellung.',
    'Sag drei Dinge, die in einer Dating-Bio niemals stehen sollten.',
    'Erfinde einen Promi-Crush für die Person gegenüber und begründe ihn.',
    'Sprich bis zu deinem nächsten Zug jedes Kompliment wie eine übertriebene Liebeserklärung aus.'
  ],

  schaetz: [
    { q: 'Wie viele Kilometer ist die Erde am Äquator ungefähr im Umfang?', a: 40075, unit: 'km' },
    { q: 'Wie viele Episoden hat die Serie Friends insgesamt?', a: 236, unit: 'Episoden' },
    { q: 'Wie viele Minuten dauert der Film Titanic von 1997 ungefähr?', a: 195, unit: 'Minuten' },
    { q: 'Wie viele Einwohner hat Berlin grob in Millionen?', a: 3.9, unit: 'Mio.' },
    { q: 'Wie viele Meter ist der Eiffelturm ungefähr hoch?', a: 330, unit: 'Meter' },
    { q: 'Wie viele Sekunden braucht Licht ungefähr von der Sonne zur Erde?', a: 500, unit: 'Sekunden' },
    { q: 'Wie viele Länder sind Mitglied der Vereinten Nationen?', a: 193, unit: 'Länder' },
    { q: 'Wie viele Oscars gewann der Film Titanic?', a: 11, unit: 'Oscars' },
    { q: 'Wie viele Spieler umfasst eine Handballmannschaft gleichzeitig auf dem Feld inklusive Torwart?', a: 7, unit: 'Spieler' },
    { q: 'Wie viele Karten hat ein klassisches UNO-Grundspiel in der neueren Standardausgabe ungefähr?', a: 112, unit: 'Karten' },
    { q: 'Wie viele Kilometer beträgt ein Marathon?', a: 42.195, unit: 'km' },
    { q: 'Wie viele Tasten hat eine typische Computertastatur in voller Größe ungefähr?', a: 105, unit: 'Tasten' },
    { q: 'Wie viele Minuten hat eine Woche?', a: 10080, unit: 'Minuten' },
    { q: 'Wie viele Felder hat ein klassisches Monopoly-Brett?', a: 40, unit: 'Felder' },
    { q: 'Wie viele Staffeln hatte Breaking Bad?', a: 5, unit: 'Staffeln' },
    { q: 'Wie viele Gramm wiegt ein Liter Wasser ungefähr bei Raumtemperatur?', a: 1000, unit: 'Gramm' },
    { q: 'Wie viele Bundesstaaten haben die USA?', a: 50, unit: 'Bundesstaaten' },
    { q: 'Wie viele Stunden dauert ein Tag auf dem Mars ungefähr?', a: 24.6, unit: 'Stunden' },
    { q: 'Wie viele Jahre dauerte der Erste Weltkrieg ungefähr?', a: 4, unit: 'Jahre' },
    { q: 'Wie viele Spieler stehen beim Volleyball pro Team gleichzeitig auf dem Feld?', a: 6, unit: 'Spieler' },
    { q: 'Wie viele Saiten hat eine Standardgitarre?', a: 6, unit: 'Saiten' },
    { q: 'Wie viele Millisekunden sind eine Sekunde?', a: 1000, unit: 'Millisekunden' },
    { q: 'Wie viele Seiten hat ein klassischer D20-Würfel?', a: 20, unit: 'Seiten' },
    { q: 'Wie viele Minuten dauert eine reguläre Halbzeit im Fußball?', a: 45, unit: 'Minuten' }
  ],

  trivia: [
    { q: 'Wer gewann die Fußball-WM 2014?', o: ['Argentinien', 'Brasilien', 'Deutschland', 'Spanien'], c: 2 },
    { q: 'Welcher Künstler veröffentlichte "Blinding Lights"?', o: ['Drake', 'The Weeknd', 'Post Malone', 'Bruno Mars'], c: 1 },
    { q: 'In welchem Jahrzehnt erschien der erste iPhone-Verkauf?', o: ['1990er', '2000er', '2010er', '2020er'], c: 1 },
    { q: 'Welche Band sang "Smells Like Teen Spirit"?', o: ['Oasis', 'Nirvana', 'Blur', 'Pearl Jam'], c: 1 },
    { q: 'Wer spielte Jack in Titanic?', o: ['Brad Pitt', 'Leonardo DiCaprio', 'Matt Damon', 'Tom Cruise'], c: 1 },
    { q: 'Welche Stadt war Austragungsort der Olympischen Sommerspiele 2012?', o: ['Paris', 'London', 'Athen', 'Tokio'], c: 1 },
    { q: 'Wie heißt der Zauberer mit der Narbe in Form eines Blitzes?', o: ['Harry Potter', 'Ron Weasley', 'Draco Malfoy', 'Neville Longbottom'], c: 0 },
    { q: 'Welches Land gewann die Fußball-WM 2018?', o: ['Kroatien', 'Frankreich', 'Deutschland', 'Argentinien'], c: 1 },
    { q: 'Welche Konsole erschien vor der PlayStation 5?', o: ['PlayStation 3', 'PlayStation 4', 'PlayStation 2', 'PSP'], c: 1 },
    { q: 'Wer sang "Shape of You"?', o: ['Ed Sheeran', 'Sam Smith', 'Harry Styles', 'Justin Bieber'], c: 0 },
    { q: 'Welche Serie spielt größtenteils in Hawkins, Indiana?', o: ['Dark', 'Stranger Things', 'Lost', 'Wednesday'], c: 1 },
    { q: 'Welcher Filmcharakter sagt sinngemäß, dass er "zurückkommen" wird?', o: ['Rocky', 'Terminator', 'Rambo', 'Neo'], c: 1 },
    { q: 'Wie heißt der grüne Oger aus der DreamWorks-Reihe?', o: ['Hulk', 'Shrek', 'Grinch', 'Fiona'], c: 1 },
    { q: 'Welches Spiel wird typischerweise auf der Map Dust II gespielt?', o: ['Valorant', 'Counter-Strike', 'Fortnite', 'Overwatch'], c: 1 },
    { q: 'Welcher Fußballer wird häufig CR7 genannt?', o: ['Cristiano Ronaldo', 'Ronaldinho', 'Ronaldo Nazário', 'Sergio Ramos'], c: 0 },
    { q: 'Welches Land gewann den Eurovision Song Contest 2024?', o: ['Schweiz', 'Schweden', 'Italien', 'Ukraine'], c: 0 },
    { q: 'Welche Fast-Food-Kette hat den Big Mac?', o: ['Burger King', 'McDonald’s', 'KFC', 'Subway'], c: 1 },
    { q: 'In welcher Filmreihe gibt es die Figur Darth Vader?', o: ['Star Trek', 'Star Wars', 'Dune', 'Matrix'], c: 1 },
    { q: 'Welcher Künstler ist für "Lose Yourself" bekannt?', o: ['50 Cent', 'Eminem', 'Dr. Dre', 'Snoop Dogg'], c: 1 },
    { q: 'Welcher Verein gewann 2024 die deutsche Fußball-Meisterschaft?', o: ['Bayern München', 'Borussia Dortmund', 'Bayer Leverkusen', 'RB Leipzig'], c: 2 },
    { q: 'Welche Sängerin veröffentlichte das Album "21"?', o: ['Adele', 'Rihanna', 'Beyoncé', 'Pink'], c: 0 },
    { q: 'Wie heißt die fiktive Stadt von Batman?', o: ['Metropolis', 'Gotham City', 'Vice City', 'Star City'], c: 1 },
    { q: 'Welches Land ist für die Stadt Dubrovnik bekannt?', o: ['Kroatien', 'Portugal', 'Griechenland', 'Malta'], c: 0 },
    { q: 'Welcher Schauspieler spielte Iron Man im MCU?', o: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'], c: 1 },
    { q: 'Welche Band veröffentlichte "Wonderwall"?', o: ['Oasis', 'Coldplay', 'U2', 'Radiohead'], c: 0 },
    { q: 'Welche Serie handelt von Walter White?', o: ['Better Call Saul', 'Breaking Bad', 'Ozark', 'Narcos'], c: 1 },
    { q: 'Welche Farbe trägt Super Mario klassischerweise auf seiner Mütze?', o: ['Blau', 'Rot', 'Grün', 'Gelb'], c: 1 },
    { q: 'Welcher Planet ist für seine auffälligen Ringe bekannt?', o: ['Mars', 'Saturn', 'Merkur', 'Venus'], c: 1 },
    { q: 'Welcher Musiker war Leadsänger von Queen?', o: ['David Bowie', 'Freddie Mercury', 'Elton John', 'George Michael'], c: 1 },
    { q: 'Welcher Film gewann 1998 den Oscar als Bester Film und handelt von einem berühmten Schiff?', o: ['Titanic', 'Apollo 13', 'Cast Away', 'Pearl Harbor'], c: 0 },
    { q: 'Welcher Sport verwendet die Begriffe Birdie und Eagle?', o: ['Tennis', 'Golf', 'Baseball', 'Eishockey'], c: 1 },
    { q: 'Welche Automarke baut den 911?', o: ['BMW', 'Porsche', 'Audi', 'Mercedes-Benz'], c: 1 },
    { q: 'Welches Land ist die Heimat von Pizza in ihrer modernen Form?', o: ['Spanien', 'Italien', 'Frankreich', 'Griechenland'], c: 1 },
    { q: 'Welche Figur lebt in einer Ananas ganz tief im Meer?', o: ['Patrick', 'SpongeBob', 'Garfield', 'Stitch'], c: 1 },
    { q: 'Welches Spiel nutzt Champions wie Ahri und Yasuo?', o: ['Dota 2', 'League of Legends', 'Smite', 'Diablo IV'], c: 1 },
    { q: 'Wer spielte den Joker in "The Dark Knight"?', o: ['Joaquin Phoenix', 'Heath Ledger', 'Jared Leto', 'Jack Nicholson'], c: 1 }
  ],

  bild: [
    { name: 'Cristiano Ronaldo', aliases: ['CR7', 'Ronaldo'], page: 'Cristiano_Ronaldo', lang: 'de' },
    { name: 'Lionel Messi', aliases: ['Messi'], page: 'Lionel_Messi', lang: 'de' },
    { name: 'Kylian Mbappé', aliases: ['Mbappe'], page: 'Kylian_Mbappé', lang: 'de' },
    { name: 'Taylor Swift', aliases: ['Taylor'], page: 'Taylor_Swift', lang: 'de' },
    { name: 'Rihanna', aliases: [], page: 'Rihanna', lang: 'de' },
    { name: 'Eminem', aliases: ['Marshall Mathers'], page: 'Eminem', lang: 'de' },
    { name: 'Snoop Dogg', aliases: ['Snoop'], page: 'Snoop_Dogg', lang: 'de' },
    { name: 'Leonardo DiCaprio', aliases: ['DiCaprio', 'Leonardo'], page: 'Leonardo_DiCaprio', lang: 'de' },
    { name: 'Dwayne Johnson', aliases: ['The Rock', 'Rock'], page: 'Dwayne_Johnson', lang: 'de' },
    { name: 'Margot Robbie', aliases: ['Margot'], page: 'Margot_Robbie', lang: 'de' },
    { name: 'Keanu Reeves', aliases: ['Keanu'], page: 'Keanu_Reeves', lang: 'de' },
    { name: 'Kim Kardashian', aliases: ['Kim'], page: 'Kim_Kardashian', lang: 'de' },
    { name: 'Kanye West', aliases: ['Ye', 'Kanye'], page: 'Kanye_West', lang: 'de' },
    { name: 'Justin Bieber', aliases: ['Bieber', 'Justin'], page: 'Justin_Bieber', lang: 'de' },
    { name: 'Adele', aliases: [], page: 'Adele_(Sängerin)', lang: 'de' },
    { name: 'Ed Sheeran', aliases: ['Ed'], page: 'Ed_Sheeran', lang: 'de' },
    { name: 'Billie Eilish', aliases: ['Billie'], page: 'Billie_Eilish', lang: 'de' },
    { name: 'Drake', aliases: [], page: 'Drake_(Rapper)', lang: 'de' },
    { name: 'The Weeknd', aliases: ['Weeknd', 'Abel Tesfaye'], page: 'The_Weeknd', lang: 'de' },
    { name: 'Bruno Mars', aliases: ['Bruno'], page: 'Bruno_Mars', lang: 'de' },
    { name: 'Tom Cruise', aliases: ['Tom'], page: 'Tom_Cruise', lang: 'de' },
    { name: 'Brad Pitt', aliases: ['Brad'], page: 'Brad_Pitt', lang: 'de' },
    { name: 'Johnny Depp', aliases: ['Johnny'], page: 'Johnny_Depp', lang: 'de' },
    { name: 'Jennifer Aniston', aliases: ['Jennifer'], page: 'Jennifer_Aniston', lang: 'de' },
    { name: 'Selena Gomez', aliases: ['Selena'], page: 'Selena_Gomez', lang: 'de' },
    { name: 'Jürgen Klopp', aliases: ['Klopp'], page: 'Jürgen_Klopp', lang: 'de' },
    { name: 'Thomas Müller', aliases: ['Müller', 'Mueller'], page: 'Thomas_Müller_(Fußballspieler)', lang: 'de' },
    { name: 'Manuel Neuer', aliases: ['Neuer'], page: 'Manuel_Neuer', lang: 'de' },
    { name: 'Lewis Hamilton', aliases: ['Hamilton'], page: 'Lewis_Hamilton', lang: 'de' },
    { name: 'Max Verstappen', aliases: ['Verstappen', 'Max'], page: 'Max_Verstappen', lang: 'de' }
  ]
};
