'use strict';

// Zusätzlicher SüffIQ-Pool für mehr Abwechslung ab v4.2.
module.exports = {
  schaetz: [
    { q: 'Wie hoch ist der Burj Khalifa ungefähr?', a: 828, unit: 'Meter' },
    { q: 'Wie weit ist der Mond im Mittel von der Erde entfernt?', a: 384400, unit: 'km' },
    { q: 'Wie alt ist die Erde ungefähr?', a: 4.54, unit: 'Milliarden Jahre' },
    { q: 'Wie groß ist der Durchmesser des Mondes ungefähr?', a: 3475, unit: 'km' },
    { q: 'Wie viele Chromosomen hat ein Mensch normalerweise in einer Körperzelle?', a: 46, unit: 'Chromosomen' },
    { q: 'Wie viele Liter Blut hat ein erwachsener Mensch ungefähr im Körper?', a: 5, unit: 'Liter' },
    { q: 'Wie viele Herzschläge hat ein Mensch grob an einem Tag?', a: 100000, unit: 'Schläge' },
    { q: 'Wie breit ist ein Fußballtor?', a: 7.32, unit: 'Meter' },
    { q: 'Wie weit ist der Elfmeterpunkt vom Fußballtor entfernt?', a: 11, unit: 'Meter' },
    { q: 'Wie hoch hängt ein Basketballkorb?', a: 3.05, unit: 'Meter' },
    { q: 'Wie viele Pins stehen beim Bowling zu Beginn eines Frames?', a: 10, unit: 'Pins' },
    { q: 'Wie viele rote Kugeln liegen beim Snooker zu Beginn auf dem Tisch?', a: 15, unit: 'Kugeln' },
    { q: 'Wie viele Zahlen hat ein europäischer Roulettekessel inklusive Null?', a: 37, unit: 'Zahlen' },
    { q: 'Wie viele Karten hat ein klassisches Pokerdeck ohne Joker?', a: 52, unit: 'Karten' },
    { q: 'In welchem Jahr fand die erste Fußball-Weltmeisterschaft statt?', a: 1930, unit: 'Jahr' },
    { q: 'In welchem Jahr startete die Fußball-Bundesliga?', a: 1963, unit: 'Jahr' },
    { q: 'In welchem Jahr begann die Formel-1-Weltmeisterschaft?', a: 1950, unit: 'Jahr' },
    { q: 'In welchem Jahr kam das erste iPhone auf den Markt?', a: 2007, unit: 'Jahr' },
    { q: 'In welchem Jahr wurde YouTube gegründet?', a: 2005, unit: 'Jahr' },
    { q: 'In welchem Jahr startete Spotify offiziell?', a: 2008, unit: 'Jahr' },
    { q: 'In welchem Jahr wurde Instagram veröffentlicht?', a: 2010, unit: 'Jahr' },
    { q: 'In welchem Jahr wurde Netflix gegründet?', a: 1997, unit: 'Jahr' },
    { q: 'In welchem Jahr wurde Google gegründet?', a: 1998, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien die erste PlayStation in Europa?', a: 1995, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien die PlayStation 5?', a: 2020, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien die Nintendo Switch?', a: 2017, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien die erste Xbox?', a: 2001, unit: 'Jahr' },
    { q: 'In welchem Jahr startete Steam?', a: 2003, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien World of Warcraft?', a: 2004, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien League of Legends?', a: 2009, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien GTA V?', a: 2013, unit: 'Jahr' },
    { q: 'In welchem Jahr erschien Counter-Strike 2?', a: 2023, unit: 'Jahr' },
    { q: 'Wie viele Episoden hat Game of Thrones insgesamt?', a: 73, unit: 'Episoden' },
    { q: 'Wie viele Episoden hat The Office (US) insgesamt?', a: 201, unit: 'Episoden' },
    { q: 'Wie viele Harry-Potter-Hauptfilme gibt es?', a: 8, unit: 'Filme' },
    { q: 'Wie viele Sekunden beträgt Usain Bolts 100-Meter-Weltrekord?', a: 9.58, unit: 'Sekunden' },
    { q: 'Wie viele Meter lang ist ein olympisches Schwimmbecken?', a: 50, unit: 'Meter' },
    { q: 'Wie viele nummerierte Segmente hat eine klassische Dartscheibe?', a: 20, unit: 'Segmente' },
    { q: 'Wie viele Kammern hat das menschliche Herz?', a: 4, unit: 'Kammern' },
    { q: 'Wie viele Monde hat die Erde?', a: 1, unit: 'Mond' },
    { q: 'Wie viele Sekunden braucht Licht ungefähr vom Mond zur Erde?', a: 1.28, unit: 'Sekunden' },
    { q: 'Wie viele Meter hoch ist der Mount Everest ungefähr?', a: 8849, unit: 'Meter' },
    { q: 'Wie viele Kilometer beträgt der Durchmesser der Erde ungefähr?', a: 12742, unit: 'km' },
    { q: 'Wie viele Liter passen ungefähr in eine normale Badewanne?', a: 150, unit: 'Liter' },
    { q: 'Wie viele Minuten sind 24 Stunden?', a: 1440, unit: 'Minuten' }
  ],

  trivia: [
    { q: 'Welcher Verein gewann die UEFA Champions League 2013?', o: ['Borussia Dortmund', 'FC Bayern München', 'Real Madrid', 'FC Barcelona'], c: 1 },
    { q: 'Welche Nation gewann die Fußball-WM 2022?', o: ['Frankreich', 'Argentinien', 'Brasilien', 'Kroatien'], c: 1 },
    { q: 'Welches Team gewann die NBA-Meisterschaft 2016?', o: ['Golden State Warriors', 'Cleveland Cavaliers', 'Miami Heat', 'Los Angeles Lakers'], c: 1 },
    { q: 'Welcher Sprinter hält den 100-Meter-Weltrekord der Männer?', o: ['Tyson Gay', 'Usain Bolt', 'Yohan Blake', 'Justin Gatlin'], c: 1 },
    { q: 'Welche Band veröffentlichte "In the End"?', o: ['Green Day', 'Linkin Park', 'Blink-182', 'Limp Bizkit'], c: 1 },
    { q: 'Wer veröffentlichte "Poker Face"?', o: ['Katy Perry', 'Lady Gaga', 'Pink', 'Rihanna'], c: 1 },
    { q: 'Von wem ist "Mr. Brightside"?', o: ['The Killers', 'Arctic Monkeys', 'Muse', 'Coldplay'], c: 0 },
    { q: 'Welche Band veröffentlichte "Numb"?', o: ['Sum 41', 'Linkin Park', 'Papa Roach', 'Evanescence'], c: 1 },
    { q: 'Wer sang "Toxic"?', o: ['Britney Spears', 'Christina Aguilera', 'Avril Lavigne', 'Shakira'], c: 0 },
    { q: 'Welcher Künstler veröffentlichte "Starboy"?', o: ['The Weeknd', 'Drake', 'Post Malone', 'Travis Scott'], c: 0 },
    { q: 'Welche Sängerin veröffentlichte "Umbrella"?', o: ['Beyoncé', 'Rihanna', 'Alicia Keys', 'Nelly Furtado'], c: 1 },
    { q: 'Welcher Film gehört nicht zum Marvel Cinematic Universe?', o: ['Iron Man', 'The Avengers', 'The Dark Knight', 'Thor'], c: 2 },
    { q: 'Wie heißt der Hauptcharakter in Breaking Bad?', o: ['Saul Goodman', 'Walter White', 'Jesse James', 'Hank Hill'], c: 1 },
    { q: 'In welcher Serie kommt die Figur Michael Scott vor?', o: ['The Office', 'Suits', 'How I Met Your Mother', 'Modern Family'], c: 0 },
    { q: 'Welche Serie spielt unter anderem in Westeros?', o: ['Vikings', 'Game of Thrones', 'The Witcher', 'The Last Kingdom'], c: 1 },
    { q: 'Wie heißt der Archäologe mit Hut und Peitsche?', o: ['Rocky Balboa', 'Indiana Jones', 'John McClane', 'Marty McFly'], c: 1 },
    { q: 'Welches Spiel stammt von Rockstar Games?', o: ['GTA V', 'Counter-Strike 2', 'League of Legends', 'Minecraft'], c: 0 },
    { q: 'Welche Firma entwickelte die PlayStation?', o: ['Nintendo', 'Microsoft', 'Sony', 'Sega'], c: 2 },
    { q: 'Welche Firma entwickelte die Xbox?', o: ['Sony', 'Microsoft', 'Valve', 'Nintendo'], c: 1 },
    { q: 'Welches Spiel besitzt die Rollen Terrorists und Counter-Terrorists?', o: ['Valorant', 'Counter-Strike', 'Rainbow Six Siege', 'Overwatch'], c: 1 },
    { q: 'Wie heißt die Währung in der Eurozone?', o: ['Dollar', 'Euro', 'Pfund', 'Franken'], c: 1 },
    { q: 'Welche Stadt ist Hauptstadt von Italien?', o: ['Mailand', 'Rom', 'Neapel', 'Turin'], c: 1 },
    { q: 'Welche Stadt ist Hauptstadt von Spanien?', o: ['Barcelona', 'Madrid', 'Valencia', 'Sevilla'], c: 1 },
    { q: 'Welche Stadt liegt am Bosporus?', o: ['Athen', 'Istanbul', 'Rom', 'Belgrad'], c: 1 },
    { q: 'Welches Element hat das Symbol Fe?', o: ['Fluor', 'Eisen', 'Fermium', 'Francium'], c: 1 },
    { q: 'Welches Element hat das Symbol O?', o: ['Gold', 'Sauerstoff', 'Osmium', 'Silber'], c: 1 },
    { q: 'Welcher Planet ist der größte im Sonnensystem?', o: ['Saturn', 'Jupiter', 'Neptun', 'Erde'], c: 1 },
    { q: 'Welcher Planet ist der Sonne am weitesten entfernt?', o: ['Uranus', 'Saturn', 'Neptun', 'Mars'], c: 2 },
    { q: 'Was misst man in Hertz?', o: ['Frequenz', 'Spannung', 'Leistung', 'Widerstand'], c: 0 },
    { q: 'Welche Einheit steht für elektrische Leistung?', o: ['Volt', 'Ampere', 'Watt', 'Ohm'], c: 2 },
    { q: 'Wie viele Spieler hat ein Handballteam gleichzeitig auf dem Feld?', o: ['5', '6', '7', '8'], c: 2 },
    { q: 'Wie lange dauert ein reguläres Handballspiel bei Erwachsenen?', o: ['40 Minuten', '50 Minuten', '60 Minuten', '70 Minuten'], c: 2 },
    { q: 'Wie hoch ist ein Basketballkorb?', o: ['2,75 m', '3,05 m', '3,35 m', '3,50 m'], c: 1 },
    { q: 'Welches Land gewann die Fußball-EM 2016?', o: ['Frankreich', 'Portugal', 'Spanien', 'Italien'], c: 1 },
    { q: 'Welches Land gewann die Fußball-EM 2024?', o: ['England', 'Frankreich', 'Spanien', 'Deutschland'], c: 2 },
    { q: 'Wer gewann 2022 die Formel-1-Fahrerweltmeisterschaft?', o: ['Lewis Hamilton', 'Charles Leclerc', 'Max Verstappen', 'Lando Norris'], c: 2 },
    { q: 'Welche Automarke trägt vier Ringe im Logo?', o: ['BMW', 'Audi', 'Volvo', 'Lexus'], c: 1 },
    { q: 'Welche Automarke hat einen Stern im Logo?', o: ['Mercedes-Benz', 'Porsche', 'Ferrari', 'Volkswagen'], c: 0 },
    { q: 'Welche deutsche Stadt ist für das Oktoberfest bekannt?', o: ['Berlin', 'Hamburg', 'München', 'Köln'], c: 2 },
    { q: 'Welche Sprache wird hauptsächlich in Argentinien gesprochen?', o: ['Portugiesisch', 'Spanisch', 'Italienisch', 'Englisch'], c: 1 }
  ],

  person: [
    { name: 'Kylian Mbappé', aliases: ['Mbappe'], hints: ['Ich wurde in Frankreich geboren.', 'Meine Geschwindigkeit gehört zu meinen größten Stärken.', '2018 wurde ich als Teenager Weltmeister.', 'Ich spielte lange für Paris Saint-Germain.', 'Mein Vorname beginnt mit K.'] },
    { name: 'Neymar', aliases: ['Neymar Jr'], hints: ['Ich komme aus Brasilien.', 'Ich wurde beim FC Santos bekannt.', 'Ich spielte gemeinsam mit Messi in Barcelona.', 'Später wechselte ich für eine damalige Rekordsumme nach Paris.', 'Mein Künstlername besteht im Fußball praktisch nur aus meinem Vornamen.'] },
    { name: 'Zlatan Ibrahimović', aliases: ['Zlatan', 'Ibrahimovic'], hints: ['Ich wurde in Schweden geboren.', 'Ich spielte für viele europäische Topvereine.', 'Akrobatische Tore wurden zu meinem Markenzeichen.', 'Ich spreche über mich selbst gern sehr selbstbewusst.', 'Mein Vorname ist Zlatan.'] },
    { name: 'Max Verstappen', aliases: ['Verstappen', 'Max'], hints: ['Ich fahre beruflich sehr schnell im Kreis.', 'Mein Vater war ebenfalls Rennfahrer.', 'Ich fahre für Red Bull Racing.', 'Ich wurde mehrfach Formel-1-Weltmeister.', 'Meine Startnummer ist seit meinem ersten Titel häufig die 1.'] },
    { name: 'Lewis Hamilton', aliases: ['Hamilton', 'Lewis'], hints: ['Ich komme aus Großbritannien.', 'Ich wurde im Motorsport berühmt.', 'Ich gewann meinen ersten Formel-1-Titel 2008.', 'Viele meiner Titel holte ich mit Mercedes.', 'Meine langjährige Startnummer ist 44.'] },
    { name: 'Freddie Mercury', aliases: ['Freddie'], hints: ['Ich wurde auf Sansibar geboren.', 'Meine Stimme wurde weltweit berühmt.', 'Ich war Frontmann einer britischen Rockband.', 'Bohemian Rhapsody gehört zu meinen bekanntesten Songs.', 'Meine Band hieß Queen.'] },
    { name: 'Britney Spears', aliases: ['Britney'], hints: ['Ich wurde als Teenager zum Popstar.', 'Ein Schuluniform-Look aus einem Musikvideo wurde ikonisch.', 'Toxic gehört zu meinen bekanntesten Songs.', 'Mein Vorname beginnt mit B.', 'Mein Nachname ist Spears.'] },
    { name: 'Beyoncé', aliases: ['Beyonce'], hints: ['Ich komme aus Houston.', 'Meine Karriere begann in einer Girlgroup.', 'Später wurde ich als Solokünstlerin weltberühmt.', 'Crazy in Love gehört zu meinen großen Hits.', 'Mein Vorname ist gleichzeitig mein Künstlername.'] },
    { name: 'Bruno Mars', aliases: ['Bruno'], hints: ['Ich wurde auf Hawaii geboren.', 'Ich bin Sänger, Songwriter und Produzent.', 'Uptown Funk machte mich zusammen mit Mark Ronson noch bekannter.', '24K Magic ist einer meiner Hits.', 'Mein Künstlernachname ist ein Planet.'] },
    { name: 'The Weeknd', aliases: ['Weeknd', 'Abel Tesfaye'], hints: ['Ich komme aus Kanada.', 'Mein bürgerlicher Vorname ist Abel.', 'Eine Zeit lang trat ich häufig mit auffälliger roter Kleidung auf.', 'Blinding Lights wurde ein riesiger Hit.', 'Mein Künstlername klingt nach einem freien Wochenende.'] },
    { name: 'Robert Downey Jr.', aliases: ['RDJ', 'Robert Downey Junior'], hints: ['Ich bin US-Schauspieler.', 'Eine meiner Figuren ist genialer Erfinder und Milliardär.', 'Diese Figur trägt einen rot-goldenen Anzug.', 'Ich spielte sie über viele Filme hinweg.', 'Gemeint ist Iron Man.'] },
    { name: 'Margot Robbie', aliases: ['Margot'], hints: ['Ich komme aus Australien.', 'Ich spielte in The Wolf of Wall Street.', 'Später verkörperte ich Harley Quinn.', '2023 spielte ich die Hauptrolle in einem sehr pinken Film.', 'Dieser Film hieß Barbie.'] },
    { name: 'Pedro Pascal', aliases: ['Pedro'], hints: ['Ich wurde in Chile geboren.', 'Ich spielte in Game of Thrones mit.', 'Ich übernahm eine Hauptrolle in Narcos.', 'Später trug ich in einer Star-Wars-Serie oft einen Helm.', 'Auch in The Last of Us spiele ich eine Hauptfigur.'] },
    { name: 'Jenna Ortega', aliases: ['Jenna'], hints: ['Ich bin US-Schauspielerin.', 'Ich war bereits als Kind vor der Kamera.', 'Eine düstere Tanzszene machte online große Wellen.', 'Ich spielte die Hauptfigur einer Netflix-Serie über die Addams Family.', 'Diese Figur heißt Wednesday.'] },
    { name: 'Gordon Ramsay', aliases: ['Ramsay'], hints: ['Ich komme aus Großbritannien.', 'Ich wurde als Koch berühmt.', 'In Fernsehsendungen werde ich häufig sehr laut.', 'Restaurants von mir erhielten Michelin-Sterne.', 'Hell’s Kitchen gehört zu meinen Shows.'] },
    { name: 'MrBeast', aliases: ['Jimmy Donaldson', 'Mr Beast'], hints: ['Ich wurde über Onlinevideos bekannt.', 'Mein bürgerlicher Name ist Jimmy Donaldson.', 'Meine Videos enthalten oft riesige Challenges und hohe Geldpreise.', 'Ich betreibe mehrere sehr große YouTube-Kanäle.', 'Mein Künstlername enthält das englische Wort für Bestie.'] }
  ],

  bild: [
    { name: 'Neymar', aliases: ['Neymar Jr'], page: 'Neymar', lang: 'de' },
    { name: 'Zlatan Ibrahimović', aliases: ['Zlatan', 'Ibrahimovic'], page: 'Zlatan_Ibrahimović', lang: 'de' },
    { name: 'Freddie Mercury', aliases: ['Freddie'], page: 'Freddie_Mercury', lang: 'de' },
    { name: 'Beyoncé', aliases: ['Beyonce'], page: 'Beyoncé', lang: 'de' },
    { name: 'Lady Gaga', aliases: ['Stefani Germanotta'], page: 'Lady_Gaga', lang: 'de' },
    { name: 'Britney Spears', aliases: ['Britney'], page: 'Britney_Spears', lang: 'de' },
    { name: 'Robert Downey Jr.', aliases: ['RDJ'], page: 'Robert_Downey_Jr.', lang: 'de' },
    { name: 'Pedro Pascal', aliases: ['Pedro'], page: 'Pedro_Pascal', lang: 'de' },
    { name: 'Jenna Ortega', aliases: ['Jenna'], page: 'Jenna_Ortega', lang: 'de' },
    { name: 'Gordon Ramsay', aliases: ['Ramsay'], page: 'Gordon_Ramsay', lang: 'de' },
    { name: 'Usain Bolt', aliases: ['Bolt'], page: 'Usain_Bolt', lang: 'de' },
    { name: 'Serena Williams', aliases: ['Serena'], page: 'Serena_Williams', lang: 'de' },
    { name: 'LeBron James', aliases: ['LeBron', 'King James'], page: 'LeBron_James', lang: 'de' },
    { name: 'Arnold Schwarzenegger', aliases: ['Arnie'], page: 'Arnold_Schwarzenegger', lang: 'de' },
    { name: 'Steve Jobs', aliases: ['Jobs'], page: 'Steve_Jobs', lang: 'de' },
    { name: 'Bill Gates', aliases: ['Gates'], page: 'Bill_Gates', lang: 'de' }
  ],

  nie: [
    'Ich hab noch nie einen Screenshot von einem Chat gemacht und ihn sofort in eine andere Gruppe geschickt.',
    'Ich hab noch nie auf einer Party so getan, als würde ich jemanden kennen.',
    'Ich hab noch nie eine Sprachnachricht aufgenommen und wegen meiner eigenen Stimme wieder gelöscht.',
    'Ich hab noch nie jemanden aus Versehen auf Social Media geliked, während ich sehr weit zurückgescrollt habe.',
    'Ich hab noch nie einen peinlichen Morgen danach erlebt.',
    'Ich hab noch nie jemanden geküsst, dessen Namen ich kurz danach vergessen hatte.',
    'Ich hab noch nie aus Neugier das Datingprofil einer bekannten Person gesucht.',
    'Ich hab noch nie eine Nachricht absichtlich erst Stunden später beantwortet.',
    'Ich hab noch nie auf einer Party behauptet, ich wäre gleich weg, und war drei Stunden später noch da.',
    'Ich hab noch nie am nächsten Morgen mein Handy kontrolliert und kurz Angst vor meinen eigenen Nachrichten gehabt.',
    'Ich hab noch nie meinen Standort geteilt und es direkt bereut.',
    'Ich hab noch nie mich auf einem Bild besser dargestellt, als der Abend wirklich war.'
  ],

  wahl: [
    'Wer würde am ehesten bei einer Schätzfrage komplett danebenliegen und trotzdem maximal selbstbewusst sein?',
    'Wer würde am ehesten bei Karaoke das Mikrofon nicht mehr hergeben?',
    'Wer würde am ehesten einen Flug verpassen, obwohl alle anderen pünktlich sind?',
    'Wer würde am ehesten nach einer Party noch einen Döner für alle organisieren?',
    'Wer würde am ehesten eine Woche ohne Social Media verlieren?',
    'Wer würde am ehesten bei einem Quiz heimlich googeln?',
    'Wer würde am ehesten einen völlig unnötigen Streit mit einem Türsteher anfangen?',
    'Wer würde am ehesten einen Promi auf der Straße zuerst erkennen?',
    'Wer würde am ehesten einen Song nach einer halben Sekunde erkennen?',
    'Wer würde am ehesten beim Schätzen absichtlich eine absurde Zahl nennen?',
    'Wer würde am ehesten spontan noch in einen anderen Club weiterziehen?',
    'Wer würde am ehesten am nächsten Morgen behaupten, der Abend sei ruhig gewesen?'
  ],

  oder: [
    ['Für immer nur 80er-Musik', 'Für immer nur 2000er-Musik'],
    ['Nie wieder YouTube', 'Nie wieder Netflix'],
    ['Immer 5 % Handy-Akku', 'Immer langsames WLAN'],
    ['WM-Finale live im Stadion', 'Lieblingsband ganz vorne live sehen'],
    ['Eine Nacht in Las Vegas', 'Eine Woche auf einer einsamen Insel'],
    ['Alle deine Suchverläufe zeigen', 'Alle deine letzten Chats zeigen'],
    ['Nur noch Sprachnachrichten', 'Nie wieder Sprachnachrichten'],
    ['Ein Jahr gratis reisen', 'Ein Jahr gratis essen gehen'],
    ['Perfektes Gedächtnis', 'Jede Sprache sprechen'],
    ['Nie wieder Kater', 'Nie wieder müde sein'],
    ['Immer den Song kennen', 'Immer jede Quizantwort kennen'],
    ['Eine Stunde zu früh', '20 Minuten zu spät']
  ],

  wahrheit: [
    'Welcher Song bringt dich sofort in Partystimmung?',
    'Was war dein größter Fehlkauf der letzten zwölf Monate?',
    'Welche Person aus dieser Runde würde dich am ehesten zu einer schlechten Idee überreden?',
    'Was ist dein peinlichster gespeicherter Kontaktname?',
    'Welche App würdest du am wenigsten gern für eine Stunde entsperrt herumgeben?',
    'Was ist dein irrationalster Abturner?',
    'Welchen Promi findest du attraktiv, obwohl deine Freunde es niemals verstehen würden?',
    'Was war dein unangenehmster Morgen nach einer Party?',
    'Welche Ausrede benutzt du viel zu oft?',
    'Was ist eine Sache, bei der du viel kompetenter wirkst, als du eigentlich bist?',
    'Welchen Song kannst du komplett mitsingen, obwohl du es niemals freiwillig zugeben würdest?',
    'Was wäre die schlimmste Person, der du heute aus Versehen schreiben könntest?'
  ],

  pflicht: [
    'Imitiere zehn Sekunden lang den schlechtesten DJ der Welt.',
    'Sing den Refrain eines Songs deiner Wahl so dramatisch wie möglich, ohne Musik abzuspielen.',
    'Mach eine 15-sekündige Siegesrede, als hättest du gerade einen Oscar gewonnen.',
    'Erfinde für die Person rechts von dir einen Wrestler-Namen.',
    'Sprich bis zur nächsten Runde wie ein übermotivierter Fußballkommentator.',
    'Stell pantomimisch einen bekannten Film dar, bis jemand ihn errät.',
    'Mach drei verschiedene Influencer-Begrüßungen hintereinander.',
    'Verkaufe dein Getränk 20 Sekunden lang wie ein Luxusprodukt.',
    'Lass die Gruppe ein Wort wählen und baue es in deine nächsten drei Sätze ein.',
    'Imitiere einen berühmten Sänger, ohne dessen Namen zu sagen.',
    'Mach deinen besten künstlichen Lachanfall für zehn Sekunden.',
    'Erfinde einen komplett absurden Fun Fact über dich und versuche die Gruppe zu überzeugen.'
  ],

  mehrheit: [
    { q: 'Welches Jahrzehnt hatte die beste Partymusik?', o: ['80er', '90er', '2000er', '2010er'] },
    { q: 'Welcher Snack gewinnt nach Mitternacht?', o: ['Döner', 'Pizza', 'Burger', 'Pommes'] },
    { q: 'Was ist schlimmer auf einer Party?', o: ['Schlechte Musik', 'Keine Getränke', 'Zu voll', 'Zu leer'] },
    { q: 'Welche Plattform könnte am ehesten eine Woche weg?', o: ['TikTok', 'Instagram', 'YouTube', 'Netflix'] },
    { q: 'Was ist die beste Art eines Quiz?', o: ['Musik', 'Sport', 'Allgemeinwissen', 'Filme/Serien'] },
    { q: 'Was wäre die beste kostenlose Sache für immer?', o: ['Flüge', 'Essen', 'Konzerte', 'Hotels'] },
    { q: 'Welche Nacht ist besser?', o: ['Club', 'Bar', 'Hausparty', 'Spieleabend'] },
    { q: 'Was ist beim Dating am wichtigsten?', o: ['Humor', 'Aussehen', 'Intelligenz', 'Ausstrahlung'] },
    { q: 'Welche Kategorie würdet ihr in SüffIQ am ehesten doppelt spielen?', o: ['Schätzen', 'Songs', 'Personen', 'Quiz'] },
    { q: 'Was ist morgens nach einer Party wichtiger?', o: ['Wasser', 'Essen', 'Schlaf', 'Kaffee'] }
  ],

  skala: [
    'Wie gut bist du bei Schätzfragen? 1 = komplett lost, 10 = menschliches Wikipedia.',
    'Wie schnell erkennst du Songs? 1 = nach dem Refrain noch nicht, 10 = erster Ton reicht.',
    'Wie gut kennst du Promis? 1 = niemand, 10 = Boulevard-Redaktion.',
    'Wie wahrscheinlich würdest du bei einem Quiz schummeln? 1 = niemals, 10 = Handy liegt schon bereit.',
    'Wie viel Partyenergie hast du gerade? 1 = Bett, 10 = Afterhour.',
    'Wie gefährlich ist dein Handy, wenn es entsperrt herumliegt? 1 = langweilig, 10 = Staatsgeheimnis.',
    'Wie gut kannst du bluffen? 1 = sofort erwischt, 10 = Pokerface.',
    'Wie wahrscheinlich erkennst du einen 2000er-Hit sofort? 1 = keine Chance, 10 = jedes Intro.',
    'Wie konkurrenzorientiert bist du gerade? 1 = völlig egal, 10 = es geht um alles.',
    'Wie wahrscheinlich machst du heute noch eine schlechte Idee mit? 1 = niemals, 10 = frag nicht, mach einfach.'
  ]
};
