'use strict';

// Zusätzliche Party-/Gruppenfragen für deutlich weniger Wiederholungen.
module.exports = {
  wahl: [
    'Wer würde am ehesten heute noch die komplette Nacht durchmachen?',
    'Wer würde am ehesten nach der Party noch eine Afterhour organisieren?',
    'Wer würde am ehesten im Club plötzlich auf der Bühne landen?',
    'Wer würde am ehesten den DJ nach einem Songwunsch nerven?',
    'Wer würde am ehesten nach zwei Drinks behaupten, komplett nüchtern zu sein?',
    'Wer würde am ehesten morgen nicht mehr wissen, wie der Abend geendet hat?',
    'Wer würde am ehesten aus Versehen im falschen Taxi landen?',
    'Wer würde am ehesten auf einer Hausparty etwas kaputtmachen?',
    'Wer würde am ehesten einen Fremden nach fünf Minuten als besten Freund bezeichnen?',
    'Wer würde am ehesten im Club die komplette Gruppe verlieren?',
    'Wer würde am ehesten spontan noch einen Kurzurlaub buchen?',
    'Wer würde am ehesten einen peinlichen Tanzmove komplett ernst meinen?',
    'Wer würde am ehesten einen Song lauter mitsingen als die Musik selbst?',
    'Wer würde am ehesten beim Vorglühen schon zu viel Gas geben?',
    'Wer würde am ehesten eine Runde für alle bestellen und es später bereuen?',
    'Wer würde am ehesten einen völlig Fremden zum Mitfeiern einladen?',
    'Wer würde am ehesten einen Club verlassen und zehn Minuten später wieder reingehen?',
    'Wer würde am ehesten einen kompletten Abend nur wegen eines guten DJs verlängern?',
    'Wer würde am ehesten am nächsten Morgen als Erstes nach Bildern vom Abend fragen?',
    'Wer würde am ehesten eine Story posten und sie am nächsten Morgen sofort löschen?',
    'Wer würde am ehesten seinen Schlüssel auf einer Party verlieren?',
    'Wer würde am ehesten sein Handy irgendwo liegen lassen?',
    'Wer würde am ehesten im Club Getränke verschütten?',
    'Wer würde am ehesten beim Karaoke plötzlich richtig gut sein?',
    'Wer würde am ehesten beim Karaoke komplett versagen und trotzdem weitermachen?',
    'Wer würde am ehesten einen 2000er-Hit nach dem ersten Ton erkennen?',
    'Wer würde am ehesten jeden David-Guetta-Refrain mitsingen können?',
    'Wer würde am ehesten bei einem Rap-Song jedes Wort kennen?',
    'Wer würde am ehesten ausgerechnet bei einem bekannten Partysong den Titel vergessen?',
    'Wer würde am ehesten bei einer Schätzfrage 100 Prozent überzeugt komplett falsch liegen?',
    'Wer würde am ehesten eine Antwort ändern und damit von richtig auf falsch wechseln?',
    'Wer würde am ehesten bei einem Quiz aus purem Glück richtig liegen?',
    'Wer würde am ehesten bei einem Quiz unnötig kompetitiv werden?',
    'Wer würde am ehesten aus Versehen die richtige Antwort verraten?',
    'Wer würde am ehesten einen Promi nur am Haarschnitt erkennen?',
    'Wer würde am ehesten einen Song erkennen, aber den Titel niemals wissen?',
    'Wer würde am ehesten beim Personenraten fünf völlig falsche Namen nacheinander nennen?',
    'Wer würde am ehesten beim verschwommenen Bild schon beim ersten Schritt richtig liegen?',
    'Wer würde am ehesten behaupten, eine Person zu kennen, obwohl er keine Ahnung hat?',
    'Wer würde am ehesten beim Trinken plötzlich philosophisch werden?',
    'Wer würde am ehesten nach Mitternacht eine tiefgründige Lebensdiskussion anfangen?',
    'Wer würde am ehesten seinem Ex schreiben?',
    'Wer würde am ehesten einen alten Crush wieder anschreiben?',
    'Wer würde am ehesten auf einer Party mit jemandem flirten, den die Gruppe niemals erwartet hätte?',
    'Wer würde am ehesten einen Flirt komplett falsch interpretieren?',
    'Wer würde am ehesten einen schlechten Anmachspruch trotzdem erfolgreich bringen?',
    'Wer würde am ehesten nach einem Date die komplette Gruppe um Rat fragen?',
    'Wer würde am ehesten einen Urlaubsflirt anfangen?',
    'Wer würde am ehesten sich in jemanden verlieben, den er eigentlich nur einmal treffen wollte?',
    'Wer würde am ehesten aus Eifersucht etwas Dummes machen?',
    'Wer würde am ehesten einen Crush viel zu lange geheim halten?',
    'Wer würde am ehesten heimlich jemanden aus dieser Runde attraktiv finden?',
    'Wer würde am ehesten auf einer Hochzeit mit jemandem verschwinden?',
    'Wer würde am ehesten beim ersten Date zu viel erzählen?',
    'Wer würde am ehesten einen Kuss anfangen?',
    'Wer würde am ehesten nach einem Kuss so tun, als wäre nichts passiert?',
    'Wer würde am ehesten eine Dating-App mitten in der Nacht neu installieren?',
    'Wer würde am ehesten ein Match sofort den Freunden zeigen?',
    'Wer würde am ehesten aus Versehen einen alten Post beim Stalken liken?',
    'Wer würde am ehesten eine peinliche Nachricht an die falsche Person schicken?',
    'Wer würde am ehesten einen Screenshot aus Versehen an genau die Person schicken, um die es geht?',
    'Wer würde am ehesten eine Sprachnachricht von fünf Minuten schicken?',
    'Wer würde am ehesten 20 ungelesene Chats haben?',
    'Wer würde am ehesten eine Woche nicht auf Nachrichten antworten?',
    'Wer würde am ehesten sofort antworten und behaupten, er habe zufällig aufs Handy geschaut?',
    'Wer würde am ehesten sein Passwort vergessen?',
    'Wer würde am ehesten den Handy-Akku bei 2 Prozent ignorieren?',
    'Wer würde am ehesten 10.000 Fotos auf dem Handy haben?',
    'Wer würde am ehesten die meisten peinlichen Screenshots besitzen?',
    'Wer würde am ehesten eine komplette Nacht TikTok schauen?',
    'Wer würde am ehesten aus Versehen live gehen?',
    'Wer würde am ehesten einen peinlichen Benutzernamen aus der Jugend noch irgendwo haben?',
    'Wer würde am ehesten auf Social Media eine Diskussion mit einem Fremden anfangen?',
    'Wer würde am ehesten eine Story nur für eine bestimmte Person posten?',
    'Wer würde am ehesten jeden in der Runde heimlich schon einmal gegoogelt haben?',
    'Wer würde am ehesten spontan 500 Euro für etwas völlig Unnötiges ausgeben?',
    'Wer würde am ehesten einen Impulskauf direkt bereuen?',
    'Wer würde am ehesten im Urlaub das meiste Geld ausgeben?',
    'Wer würde am ehesten beim Bestellen viel zu viel Essen nehmen?',
    'Wer würde am ehesten nachts noch Fast Food bestellen?',
    'Wer würde am ehesten für einen Döner einen riesigen Umweg machen?',
    'Wer würde am ehesten das letzte Stück Pizza nehmen, ohne zu fragen?',
    'Wer würde am ehesten beim Kochen die Küche zerstören?',
    'Wer würde am ehesten ein Rezept komplett ignorieren?',
    'Wer würde am ehesten morgens nur mit Kaffee funktionieren?',
    'Wer würde am ehesten eine Woche nur von Lieferdienst leben?',
    'Wer würde am ehesten im Restaurant immer dasselbe bestellen?',
    'Wer würde am ehesten beim All-you-can-eat zu ehrgeizig werden?',
    'Wer würde am ehesten eine scharfe Challenge gewinnen?',
    'Wer würde am ehesten eine scharfe Challenge sofort bereuen?',
    'Wer würde am ehesten spontan 1000 Kilometer mit dem Auto fahren?',
    'Wer würde am ehesten einen Flug verpassen?',
    'Wer würde am ehesten den Reisepass zuhause vergessen?',
    'Wer würde am ehesten im Urlaub ohne Plan loslaufen und sich verlaufen?',
    'Wer würde am ehesten eine Reise komplett durchplanen?',
    'Wer würde am ehesten einen Roadtrip organisieren?',
    'Wer würde am ehesten im Ausland mit Händen und Füßen kommunizieren?',
    'Wer würde am ehesten im Urlaub jemanden kennenlernen und danach Kontakt halten?',
    'Wer würde am ehesten im Urlaub jeden Morgen früh aufstehen?',
    'Wer würde am ehesten im Urlaub bis mittags schlafen?',
    'Wer würde am ehesten im Hotel etwas liegen lassen?',
    'Wer würde am ehesten spontan auswandern?',
    'Wer würde am ehesten einen Marathon anfangen, ohne genug trainiert zu haben?',
    'Wer würde am ehesten bei einem Sportturnier viel zu ehrgeizig werden?',
    'Wer würde am ehesten eine Verletzung ignorieren und weiterspielen?',
    'Wer würde am ehesten im Fitnessstudio mehr Gewicht nehmen, als sinnvoll wäre?',
    'Wer würde am ehesten einen neuen Sport ausprobieren und sofort süchtig werden?',
    'Wer würde am ehesten beim Fußball eine rote Karte kassieren?',
    'Wer würde am ehesten beim Handball eine Zwei-Minuten-Strafe wegen Meckerns bekommen?',
    'Wer würde am ehesten beim Brettspiel Streit anfangen?',
    'Wer würde am ehesten bei Mario Kart Freundschaften gefährden?',
    'Wer würde am ehesten bei FIFA oder EA FC den Controller weglegen und behaupten, das Spiel sei schuld?',
    'Wer würde am ehesten bei Counter-Strike nach einer Niederlage noch eine Runde starten?',
    'Wer würde am ehesten die ganze Nacht zocken?',
    'Wer würde am ehesten bei einem Escape Room die Gruppe retten?',
    'Wer würde am ehesten bei einem Escape Room komplett nutzlos sein?',
    'Wer würde am ehesten bei Monopoly schummeln?',
    'Wer würde am ehesten bei Uno eine Freundschaft wegen einer +4 riskieren?',
    'Wer würde am ehesten eine Wette viel zu ernst nehmen?',
    'Wer würde am ehesten eine dumme Wette trotzdem durchziehen?',
    'Wer würde am ehesten spontan einen neuen Haarschnitt ausprobieren?',
    'Wer würde am ehesten sich ein Tattoo spontan stechen lassen?',
    'Wer würde am ehesten einen peinlichen Spitznamen dauerhaft behalten?',
    'Wer würde am ehesten bei einer Gameshow gewinnen?',
    'Wer würde am ehesten Reality-TV überleben?',
    'Wer würde am ehesten aus Versehen viral gehen?',
    'Wer würde am ehesten als Influencer durchstarten?',
    'Wer würde am ehesten berühmt werden und trotzdem dieselbe Person bleiben?',
    'Wer würde am ehesten einen Promi ansprechen?',
    'Wer würde am ehesten einen Promi sehen und sich nicht trauen, etwas zu sagen?',
    'Wer würde am ehesten bei einem Konzert ganz vorne stehen?',
    'Wer würde am ehesten sein Handy bei einem Konzert die ganze Zeit wegpacken?',
    'Wer würde am ehesten spontan auf ein Festival fahren?',
    'Wer würde am ehesten auf einem Festival sein Zelt nicht mehr finden?',
    'Wer würde am ehesten drei Tage Festival am besten überstehen?',
    'Wer würde am ehesten schon am ersten Festivaltag komplett fertig sein?',
    'Wer würde am ehesten einen Song komplett falsch mitsingen und es nie merken?',
    'Wer würde am ehesten die Playlist für die ganze Gruppe übernehmen?',
    'Wer würde am ehesten die beste Partyplaylist haben?',
    'Wer würde am ehesten einen Song skippen, den alle anderen lieben?',
    'Wer würde am ehesten bei einem 90er-Hit sofort aufstehen?',
    'Wer würde am ehesten bei einem 2000er-Hit komplett eskalieren?',
    'Wer würde am ehesten bei Deutschrap jedes Wort kennen?',
    'Wer würde am ehesten bei einem Schlager plötzlich textsicher sein?',
    'Wer würde am ehesten bei einem Rockklassiker die Luftgitarre auspacken?',
    'Wer würde am ehesten den Musikgeschmack der Gruppe am stärksten ruinieren?',
    'Wer würde am ehesten heute als Letztes schlafen gehen?',
    'Wer würde am ehesten morgen den schlimmsten Kater haben?',
    'Wer würde am ehesten behaupten, nie einen Kater zu bekommen?',
    'Wer würde am ehesten morgen trotzdem um 8 Uhr fit sein?',
    'Wer würde am ehesten heute eine Entscheidung treffen, die morgen erklärt werden muss?',
    'Wer würde am ehesten heute noch eine legendäre Story produzieren?',
    'Wer würde am ehesten dafür sorgen, dass der Abend komplett eskaliert?',
    'Wer würde am ehesten die Gruppe sicher nach Hause bringen?',
    'Wer würde am ehesten am Ende alle Jacken und Handys einsammeln?',
    'Wer würde am ehesten morgen als Erstes schreiben: Was ist gestern passiert?'
  ],

  nie: [
    'Ich hab noch nie im Club einen Songwunsch beim DJ abgegeben.',
    'Ich hab noch nie so getan, als würde ich einen Song kennen, obwohl ich ihn nicht kannte.',
    'Ich hab noch nie nach einer Party meine Storys vom Vorabend gelöscht.',
    'Ich hab noch nie morgens Angst gehabt, meine gesendeten Nachrichten zu öffnen.',
    'Ich hab noch nie auf einer Party jemanden kennengelernt und den Namen direkt wieder vergessen.',
    'Ich hab noch nie einen Abend verlängert, obwohl ich eigentlich längst gehen wollte.',
    'Ich hab noch nie einen Song so laut mitgesungen, dass andere mich gehört haben.',
    'Ich hab noch nie bei Karaoke einen Song gewählt, den ich eigentlich nicht konnte.',
    'Ich hab noch nie einen Kater mit Fast Food behandelt.',
    'Ich hab noch nie auf einem Festival mein Zelt oder meine Gruppe gesucht.',
    'Ich hab noch nie nach einem Abend Bilder entdeckt, an die ich mich nicht erinnern konnte.',
    'Ich hab noch nie jemanden auf einer Party für jemand anderen gehalten.',
    'Ich hab noch nie einen peinlichen Tanzmove absichtlich wiederholt.',
    'Ich hab noch nie behauptet, nur einen Drink zu nehmen, und bin viel länger geblieben.',
    'Ich hab noch nie eine komplette Partyplaylist an mich gerissen.',
    'Ich hab noch nie wegen eines Songs sofort meine Stimmung geändert.',
    'Ich hab noch nie bei einem Spiel viel zu ehrgeizig reagiert.',
    'Ich hab noch nie eine dumme Wette angenommen, nur weil alle zugeschaut haben.',
    'Ich hab noch nie aus Versehen etwas in die falsche Gruppe geschickt.',
    'Ich hab noch nie einen alten Crush gestalkt und dabei viel zu weit zurückgescrollt.',
    'Ich hab noch nie einen Chat geöffnet und absichtlich nicht geantwortet.',
    'Ich hab noch nie so getan, als hätte ich eine Nachricht nicht gesehen.',
    'Ich hab noch nie nach einem Date sofort eine Gruppenanalyse gestartet.',
    'Ich hab noch nie aus Langeweile eine Dating-App geöffnet.',
    'Ich hab noch nie jemanden attraktiver gefunden, nachdem ich ihn besser kennengelernt habe.',
    'Ich hab noch nie einen Flirt komplett falsch eingeschätzt.',
    'Ich hab noch nie eine Nachricht fünfmal umformuliert, bevor ich sie abgeschickt habe.',
    'Ich hab noch nie einen Screenshot gemacht, den die betroffene Person niemals sehen dürfte.',
    'Ich hab noch nie nachts Essen bestellt und am nächsten Morgen die Bestellung bereut.',
    'Ich hab noch nie im Urlaub etwas Wichtiges vergessen.'
  ],

  wahrheit: [
    'Wer aus dieser Runde wäre dein gefährlichster Party-Buddy?',
    'Mit wem aus dieser Runde würdest du am ehesten spontan in den Urlaub fliegen?',
    'Welcher Song bringt dich innerhalb von fünf Sekunden auf die Tanzfläche?',
    'Welcher Song ist dein heimlicher Party-Guilty-Pleasure?',
    'Was war dein wildester Partyabend?',
    'Was war dein schlimmster Kater?',
    'Was ist das Peinlichste, das dir beim Feiern passiert ist?',
    'Welche Nachricht würdest du nach drei Drinks am ehesten bereuen?',
    'Welchen Promi würdest du sofort auf einen Drink einladen?',
    'Was ist dein schlimmster Tanzmove?',
    'Was ist deine größte Red Flag beim Dating?',
    'Was ist deine eigene größte Red Flag?',
    'Was ist das Dümmste, das du je aus Eifersucht gemacht hast?',
    'Welche Person aus deiner Vergangenheit würdest du aus Neugier gern wiedersehen?',
    'Welcher Chat wäre dir gerade am unangenehmsten, wenn er auf dem Fernseher angezeigt würde?',
    'Was war dein schlechtester Anmachspruch?',
    'Wann hast du zuletzt jemanden absichtlich warten lassen?',
    'Was ist eine Sache, die du nach Mitternacht viel eher tun würdest als tagsüber?',
    'Was war deine spontanste schlechte Idee?',
    'Welche schlechte Idee würdest du trotzdem wieder machen?',
    'Was war dein unnötigster Kauf nach einer Party oder nachts?',
    'Welche App sollte heute niemand aus dieser Runde auf deinem Handy öffnen?',
    'Welches Foto auf deinem Handy müsste als Erstes verschwinden?',
    'Welche Person hier würdest du am ehesten als Wingman oder Wingwoman nehmen?',
    'Was ist etwas, das du nüchtern nie machen würdest, auf einer Party aber vielleicht schon?'
  ],

  pflicht: [
    'Mach 15 Sekunden lang deinen besten Club-Tanzmove.',
    'Imitiere einen DJ kurz vor dem Drop.',
    'Sing zehn Sekunden lang einen Partyhit deiner Wahl ohne Musik.',
    'Mach eine komplett übertriebene Festival-Ansage.',
    'Erfinde einen neuen Namen für die Party und kündige sie wie ein Event an.',
    'Flirte zehn Sekunden lang mit deinem Getränk.',
    'Imitiere die Person links von dir beim Feiern.',
    'Imitiere die Person rechts von dir beim Tanzen.',
    'Mach einen imaginären Red-Carpet-Auftritt durch den Raum.',
    'Gib eine zehnsekündige Dankesrede für deinen Lieblings-Partysong.',
    'Erfinde einen schlechten Rap über die Runde.',
    'Freestyle zehn Sekunden über das Wort SüffIQ.',
    'Mach deinen besten Air-Guitar-Move.',
    'Tanze zehn Sekunden zu einem Song, den nur du im Kopf hörst.',
    'Sprich den nächsten Satz wie ein überdrehter Club-Promoter.',
    'Erfinde einen Anmachspruch für die Person gegenüber.',
    'Mach ein völlig übertriebenes Kompliment an die Person links von dir.',
    'Stell einen bekannten Musiker pantomimisch dar, bis jemand ihn erkennt.',
    'Mach eine Sportkommentator-Ansage über jemanden, der gerade sein Getränk nimmt.',
    'Verkaufe dein aktuelles Getränk wie ein Luxusprodukt.',
    'Erfinde eine absurd schlechte Dating-Bio für dich selbst.',
    'Mach ein Selfie-Gesicht aus dem Jahr 2012.',
    'Imitiere einen Influencer bei einer völlig unnötigen Produktwerbung.',
    'Erfinde für jede Person in der Runde einen Festival-Spitznamen.',
    'Halte 15 Sekunden lang eine Motivationsrede, warum diese Party noch lange nicht vorbei ist.'
  ],

  oder: [
    ['Nur noch 2000er-Partyhits', 'Nur noch 2010er-Festivalhits'],
    ['David Guetta für immer', 'Avicii für immer'],
    ['Deutschrap-Party', 'EDM-Party'],
    ['Hausparty', 'Festival'],
    ['Club bis 5 Uhr', 'Bar bis 2 Uhr'],
    ['Nie wieder Karaoke', 'Nie wieder Tanzen'],
    ['Immer den Songtitel kennen', 'Immer den Interpreten kennen'],
    ['VIP-Bereich', 'Ganz vorne vor der Bühne'],
    ['Eine Woche Ibiza', 'Eine Woche Las Vegas'],
    ['Nur noch Rap', 'Nur noch elektronische Musik'],
    ['Jeden Song mitsingen können', 'Jeden Tanzmove perfekt können'],
    ['Nie wieder Kater', 'Nie wieder müde nach einer Party'],
    ['Peinliche Chats veröffentlichen', 'Peinliche Fotos veröffentlichen'],
    ['Ein Jahr keine Partys', 'Ein Jahr keine Streamingdienste'],
    ['Immer die Playlist bestimmen', 'Immer die Location bestimmen'],
    ['Festival im Regen', 'Club ohne Klimaanlage'],
    ['Letzter im Club sein', 'Erster auf der Afterhour sein'],
    ['Jeden Song nach einer Sekunde erkennen', 'Jede Schätzfrage perfekt treffen'],
    ['Nur noch Hauspartys', 'Nur noch Festivals'],
    ['DJ sein', 'Auf der Bühne stehen']
  ],

  mehrheit: [
    { q: 'Welcher Artist rettet eine Party am ehesten?', o: ['David Guetta', 'Avicii', 'Pitbull', '50 Cent'] },
    { q: 'Welche Musikrichtung funktioniert nachts am besten?', o: ['EDM', 'Rap', '2000er', 'Deutschrap'] },
    { q: 'Welches Jahrzehnt hatte die besten Clubhits?', o: ['90er', '2000er', '2010er', '2020er'] },
    { q: 'Was ist die beste Party-Location?', o: ['Hausparty', 'Club', 'Festival', 'Bar'] },
    { q: 'Was ist nach Mitternacht am wichtigsten?', o: ['Musik', 'Essen', 'Leute', 'Energie'] },
    { q: 'Welches Fast Food gewinnt nach einer langen Nacht?', o: ['Döner', 'Pizza', 'Burger', 'Pommes'] },
    { q: 'Was nervt auf einer Party am meisten?', o: ['Schlechte Musik', 'Zu voll', 'Zu heiß', 'Leere Drinks'] },
    { q: 'Was macht den besseren Partyhit aus?', o: ['Bass', 'Refrain', 'Beat', 'Erinnerungen'] },
    { q: 'Welche Runde in SüffIQ sollte häufiger kommen?', o: ['Schätzen', 'Songs', 'Personen', 'Wer würde eher'] },
    { q: 'Was ist morgens nach einer Party am wichtigsten?', o: ['Wasser', 'Schlaf', 'Essen', 'Kaffee'] },
    { q: 'Welche Partyära gewinnt?', o: ['90er Eurodance', '2000er Club', '2010er EDM', 'aktueller Rap'] },
    { q: 'Was ist beim Festival am wichtigsten?', o: ['Line-up', 'Leute', 'Wetter', 'Campingplatz'] },
    { q: 'Welcher Moment ist besser?', o: ['Der erste Song', 'Der erste Drop', 'Der Lieblingssong', 'Der letzte Song'] },
    { q: 'Was ist schlimmer zu verlieren?', o: ['Handy', 'Schlüssel', 'Freunde', 'Jacke'] },
    { q: 'Was ist die beste Vorbereitung auf eine lange Nacht?', o: ['Essen', 'Schlaf', 'Playlist', 'Gar keine'] }
  ],

  skala: [
    'Wie groß ist deine Partyenergie gerade? 1 = Bett, 10 = Afterhour.',
    'Wie schnell erkennst du Partyhits? 1 = nie, 10 = erster Ton.',
    'Wie textsicher bist du bei 2000er-Hits? 1 = gar nicht, 10 = jedes Wort.',
    'Wie textsicher bist du bei Rap? 1 = gar nicht, 10 = jede Line.',
    'Wie wahrscheinlich übernimmst du die Playlist? 1 = nie, 10 = sofort.',
    'Wie wahrscheinlich tanzt du heute noch? 1 = niemals, 10 = sicher.',
    'Wie wahrscheinlich bleibst du bis ganz zum Schluss? 1 = bald weg, 10 = Licht geht an.',
    'Wie gefährlich ist dein Handy nach Mitternacht? 1 = völlig harmlos, 10 = Flugmodus wäre besser.',
    'Wie wahrscheinlich schreibst du heute noch jemandem, dem du nicht schreiben solltest? 1 = nie, 10 = Handy wegnehmen.',
    'Wie gut kannst du einen Kater verstecken? 1 = unmöglich, 10 = Profi.',
    'Wie gut bist du bei Wer-würde-eher-Fragen? 1 = keine Ahnung, 10 = kenne alle zu gut.',
    'Wie kompetitiv wirst du bei SüffIQ? 1 = egal, 10 = Weltmeisterschaft.',
    'Wie spontan bist du nachts? 1 = direkt heim, 10 = nächste Stadt.',
    'Wie wahrscheinlich würdest du auf einem Festival dein Zelt verlieren? 1 = nie, 10 = garantiert.',
    'Wie wahrscheinlich würdest du Karaoke machen? 1 = niemals, 10 = Mikro her.'
  ]
};
