'use strict';

// SüffIQ v2: 240 eigene Karten, 24 pro Kategorie.
module.exports = {
  nie: [
    'Ich hab noch nie aus Versehen eine Nachricht an die falsche Person geschickt.',
    'Ich hab noch nie einen Wecker ausgeschaltet und danach behauptet, er hätte nicht geklingelt.',
    'Ich hab noch nie Essen vom Boden aufgehoben und trotzdem gegessen.',
    'Ich hab noch nie bei einem Film so getan, als hätte ich ihn verstanden.',
    'Ich hab noch nie einen Geburtstag vergessen und erst durch Social Media daran gedacht.',
    'Ich hab noch nie jemanden gegoogelt, bevor ich ihn zum ersten Mal getroffen habe.',
    'Ich hab noch nie im Auto laut gesungen und an der Ampel abrupt aufgehört.',
    'Ich hab noch nie einen Screenshot gemacht, um ihn direkt weiterzuschicken.',
    'Ich hab noch nie einen ganzen Tag im Schlafanzug verbracht.',
    'Ich hab noch nie eine Serie ohne die Person weitergeschaut, mit der ich sie angefangen habe.',
    'Ich hab noch nie so getan, als wäre mein Akku leer, um nicht antworten zu müssen.',
    'Ich hab noch nie im Supermarkt etwas probiert, bevor ich es bezahlt habe.',
    'Ich hab noch nie einen Namen vergessen, obwohl die Person ihn gerade gesagt hat.',
    'Ich hab noch nie einen Termin abgesagt, weil ich einfach keine Lust hatte.',
    'Ich hab noch nie beim Kochen etwas verbrannt und es trotzdem serviert.',
    'Ich hab noch nie heimlich die letzte Portion gegessen.',
    'Ich hab noch nie auf einer Party jemanden mit dem falschen Namen angesprochen.',
    'Ich hab noch nie beim Sport eine Verletzung dramatischer dargestellt, als sie war.',
    'Ich hab noch nie ein Geschenk weiter verschenkt.',
    'Ich hab noch nie mich selbst im Spiegel erschreckt, weil ich nicht aufgepasst habe.',
    'Ich hab noch nie einen Song komplett falsch mitgesungen und es erst später gemerkt.',
    'Ich hab noch nie eine Ausrede benutzt, die offensichtlich erfunden war.',
    'Ich hab noch nie bei einer Diskussion so getan, als hätte ich eine Quelle gelesen.',
    'Ich hab noch nie mein Handy gesucht, während ich es in der Hand hatte.'
  ],

  wahl: [
    'Wer würde am ehesten einen spontanen Roadtrip starten?',
    'Wer würde am ehesten beim Karaoke komplett eskalieren?',
    'Wer würde am ehesten eine Woche ohne Handy durchhalten?',
    'Wer würde am ehesten zu spät zur eigenen Hochzeit kommen?',
    'Wer würde am ehesten in einer Gameshow gewinnen?',
    'Wer würde am ehesten aus Versehen berühmt werden?',
    'Wer würde am ehesten mitten in der Nacht noch Essen bestellen?',
    'Wer würde am ehesten beim Camping als Erstes aufgeben?',
    'Wer würde am ehesten eine peinliche Story freiwillig erzählen?',
    'Wer würde am ehesten eine wilde Wette annehmen?',
    'Wer würde am ehesten einen ganzen Urlaub durchplanen?',
    'Wer würde am ehesten eine Party retten, wenn die Stimmung kippt?',
    'Wer würde am ehesten bei einem Escape Room die Lösung finden?',
    'Wer würde am ehesten einen fremden Hund sofort zum besten Freund machen?',
    'Wer würde am ehesten bei einem Brettspiel zu ehrgeizig werden?',
    'Wer würde am ehesten eine Woche nur von Snacks leben?',
    'Wer würde am ehesten einen peinlichen Spitznamen bekommen?',
    'Wer würde am ehesten beim ersten Date etwas umwerfen?',
    'Wer würde am ehesten eine verrückte Geschäftsidee wirklich umsetzen?',
    'Wer würde am ehesten im Urlaub den Reisepass vergessen?',
    'Wer würde am ehesten einen Tag lang mit einem Promi tauschen wollen?',
    'Wer würde am ehesten eine Nacht durchtanzen?',
    'Wer würde am ehesten eine Challenge viel zu ernst nehmen?',
    'Wer würde am ehesten morgen spontan die Haare komplett anders tragen?'
  ],

  schaetz: [
    { q: 'Wie viele Minuten hat ein Tag?', a: 1440, unit: 'Minuten' },
    { q: 'Wie viele Tasten hat ein klassisches Klavier?', a: 88, unit: 'Tasten' },
    { q: 'Wie viele Karten hat ein normales Skatblatt?', a: 32, unit: 'Karten' },
    { q: 'Wie viele Felder hat ein Schachbrett?', a: 64, unit: 'Felder' },
    { q: 'Wie viele Sekunden hat eine Stunde?', a: 3600, unit: 'Sekunden' },
    { q: 'Wie viele Knochen hat ein erwachsener Mensch ungefähr?', a: 206, unit: 'Knochen' },
    { q: 'Wie viele Zähne hat ein Erwachsener normalerweise inklusive Weisheitszähnen?', a: 32, unit: 'Zähne' },
    { q: 'Wie viele Länder grenzen an Deutschland?', a: 9, unit: 'Länder' },
    { q: 'Wie viele Ringe hat das olympische Symbol?', a: 5, unit: 'Ringe' },
    { q: 'Wie viele Spieler stehen beim Fußball pro Team regulär gleichzeitig auf dem Feld?', a: 11, unit: 'Spieler' },
    { q: 'Wie viele Minuten dauert ein reguläres Handballspiel der Erwachsenen?', a: 60, unit: 'Minuten' },
    { q: 'Wie viele Sterne hat die Flagge der Europäischen Union?', a: 12, unit: 'Sterne' },
    { q: 'Wie viele Bundesländer hat Deutschland?', a: 16, unit: 'Bundesländer' },
    { q: 'Wie viele Seiten hat ein Würfel?', a: 6, unit: 'Seiten' },
    { q: 'Wie viele Nullen hat eine Milliarde?', a: 9, unit: 'Nullen' },
    { q: 'Wie viele Elemente hatte das Periodensystem mit offiziell benannten Elementen seit 2016?', a: 118, unit: 'Elemente' },
    { q: 'Wie viele Jahre liegen zwischen 2000 und 2025?', a: 25, unit: 'Jahre' },
    { q: 'Wie viele Stunden hat eine Woche?', a: 168, unit: 'Stunden' },
    { q: 'Wie viele Monate haben genau 31 Tage?', a: 7, unit: 'Monate' },
    { q: 'Wie viele Buchstaben hat das deutsche Alphabet ohne Umlaute und ß?', a: 26, unit: 'Buchstaben' },
    { q: 'Wie viele Meter sind ein Kilometer?', a: 1000, unit: 'Meter' },
    { q: 'Wie viele Milliliter sind ein Liter?', a: 1000, unit: 'Milliliter' },
    { q: 'Wie viele Grad hat ein voller Kreis?', a: 360, unit: 'Grad' },
    { q: 'Wie viele Tage hat ein Schaltjahr?', a: 366, unit: 'Tage' }
  ],

  oder: [
    ['Nie wieder Musik hören', 'Nie wieder Filme oder Serien schauen'],
    ['Immer 30 Minuten zu früh', 'Immer 10 Minuten zu spät'],
    ['Nur noch süß essen', 'Nur noch salzig essen'],
    ['Ein Jahr ohne Social Media', 'Ein Jahr ohne Streaming'],
    ['Gedanken lesen können', 'Unsichtbar sein können'],
    ['Immer Sommer', 'Immer Winter'],
    ['Nur noch bar zahlen', 'Nur noch mit Karte zahlen'],
    ['Berge', 'Meer'],
    ['Früh aufstehen', 'Lange wach bleiben'],
    ['Karaoke', 'Tanzen'],
    ['Spontan reisen', 'Alles vorher planen'],
    ['Kaffee', 'Energy'],
    ['Hund', 'Katze'],
    ['Stadtleben', 'Landleben'],
    ['Nie wieder Fast Food', 'Nie wieder Süßigkeiten'],
    ['Zeit anhalten', 'Zeit zurückdrehen'],
    ['Immer die Wahrheit sagen', 'Nie wieder sprechen'],
    ['Nur noch Serien', 'Nur noch Filme'],
    ['Camping', 'Hotel'],
    ['Kochen', 'Bestellen'],
    ['Party zuhause', 'Party im Club'],
    ['Spieleabend', 'Kinoabend'],
    ['Einen Monat ohne Auto', 'Einen Monat ohne Handy'],
    ['Immer Glück haben', 'Immer perfekt vorbereitet sein']
  ],

  trivia: [
    { q: 'Welcher Planet ist der Sonne am nächsten?', o: ['Venus', 'Mars', 'Merkur', 'Erde'], c: 2 },
    { q: 'Welche Farbe entsteht aus Blau und Gelb?', o: ['Grün', 'Orange', 'Lila', 'Braun'], c: 0 },
    { q: 'Wie heißt die Hauptstadt von Portugal?', o: ['Porto', 'Lissabon', 'Madrid', 'Faro'], c: 1 },
    { q: 'Welches Tier ist das größte heute lebende Landtier?', o: ['Nashorn', 'Giraffe', 'Afrikanischer Elefant', 'Nilpferd'], c: 2 },
    { q: 'Welches chemische Symbol hat Gold?', o: ['Ag', 'Au', 'Gd', 'Go'], c: 1 },
    { q: 'Welcher Ozean ist der größte?', o: ['Atlantik', 'Indischer Ozean', 'Arktischer Ozean', 'Pazifik'], c: 3 },
    { q: 'Wie viele Kontinente werden im üblichen Sieben-Kontinente-Modell gezählt?', o: ['5', '6', '7', '8'], c: 2 },
    { q: 'Welches Organ pumpt Blut durch den Körper?', o: ['Leber', 'Herz', 'Lunge', 'Niere'], c: 1 },
    { q: 'Wie heißt der höchste Berg der Erde über dem Meeresspiegel?', o: ['K2', 'Mont Blanc', 'Mount Everest', 'Kilimandscharo'], c: 2 },
    { q: 'Welche Sprache wird in Brasilien hauptsächlich gesprochen?', o: ['Spanisch', 'Portugiesisch', 'Französisch', 'Englisch'], c: 1 },
    { q: 'Wer malte die Mona Lisa?', o: ['Michelangelo', 'Picasso', 'Leonardo da Vinci', 'Van Gogh'], c: 2 },
    { q: 'Welches Gas nehmen Pflanzen für die Photosynthese auf?', o: ['Sauerstoff', 'Stickstoff', 'Kohlendioxid', 'Helium'], c: 2 },
    { q: 'Wie heißt die Hauptstadt von Kanada?', o: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], c: 2 },
    { q: 'Welcher Kontinent ist flächenmäßig der größte?', o: ['Afrika', 'Asien', 'Europa', 'Nordamerika'], c: 1 },
    { q: 'Welche Zahl ist eine Primzahl?', o: ['21', '27', '29', '33'], c: 2 },
    { q: 'Wie heißt die Währung Japans?', o: ['Won', 'Yen', 'Yuan', 'Rupie'], c: 1 },
    { q: 'Welche Sportart nutzt einen Federball?', o: ['Squash', 'Badminton', 'Tennis', 'Padel'], c: 1 },
    { q: 'Welches Metall ist bei Raumtemperatur flüssig?', o: ['Quecksilber', 'Aluminium', 'Kupfer', 'Eisen'], c: 0 },
    { q: 'Welcher Planet wird oft roter Planet genannt?', o: ['Jupiter', 'Mars', 'Saturn', 'Neptun'], c: 1 },
    { q: 'Wie heißt die Hauptstadt von Australien?', o: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], c: 2 },
    { q: 'Welche Einheit misst elektrische Spannung?', o: ['Ampere', 'Volt', 'Watt', 'Ohm'], c: 1 },
    { q: 'Welches Meer liegt zwischen Europa und Afrika?', o: ['Nordsee', 'Mittelmeer', 'Ostsee', 'Schwarzes Meer'], c: 1 },
    { q: 'Welche Form hat drei Seiten?', o: ['Quadrat', 'Dreieck', 'Fünfeck', 'Kreis'], c: 1 },
    { q: 'Wie heißt das größte Organ des menschlichen Körpers?', o: ['Herz', 'Leber', 'Haut', 'Lunge'], c: 2 }
  ],

  wahrheit: [
    'Was war dein peinlichster Moment in der Schule oder Ausbildung?',
    'Welche Angewohnheit von dir nervt dich selbst am meisten?',
    'Was war die schlechteste Ausrede, die du je benutzt hast?',
    'Wann hast du zuletzt so getan, als würdest du jemanden nicht sehen?',
    'Welchen Song hörst du heimlich gern?',
    'Was war dein unnötigster Kauf?',
    'Wovor hattest du als Kind völlig unbegründet Angst?',
    'Welche App öffnest du viel zu oft?',
    'Was ist dein seltsamstes Talent?',
    'Welche Kleinigkeit macht dich sofort aggressiv?',
    'Welchen Trend hast du nie verstanden?',
    'Was würdest du an deinem letzten Urlaub anders machen?',
    'Was war dein schlimmster Koch-Fail?',
    'Welche Serie hast du viel zu schnell durchgeschaut?',
    'Was war dein letzter spontaner Kauf?',
    'Welche Sache schiebst du seit Wochen vor dir her?',
    'Was ist die unnötigste Diskussion, die du je geführt hast?',
    'Welche berühmte Person würdest du gern einen Tag lang treffen?',
    'Was ist dein unpraktischstes Lieblingsessen?',
    'Was war dein schlimmster Mode-Fail?',
    'Wann hast du zuletzt gelogen, um aus einer Situation rauszukommen?',
    'Welche Sache kannst du schlechter als fast alle hier?',
    'Was würdest du sofort lernen, wenn es nur einen Tag dauern würde?',
    'Welche Entscheidung hast du komplett spontan getroffen und nie bereut?'
  ],

  pflicht: [
    'Sprich bis zum Ende der Runde mit übertrieben seriöser Nachrichtensprecher-Stimme.',
    'Mach 10 saubere Kniebeugen.',
    'Imitiere 20 Sekunden lang einen Sportkommentator.',
    'Lass die Gruppe dir einen neuen Spitznamen für drei Runden geben.',
    'Erfinde einen Werbeslogan für dein aktuelles Getränk.',
    'Mach ein Tiergeräusch, bis jemand das Tier errät.',
    'Erkläre deinen letzten Snack wie ein Sternekoch.',
    'Tanze 15 Sekunden ohne Musik.',
    'Sprich den nächsten Satz, als wärst du in einem Actionfilm.',
    'Mach ein Gruppenfoto mit der dramatischsten Pose, die ihr hinbekommt.',
    'Nenne fünf Städte in zehn Sekunden.',
    'Versuche 15 Sekunden lang nicht zu lachen, während die anderen dich ablenken.',
    'Erfinde eine kurze Hymne für die Runde und singe eine Zeile davon.',
    'Mach einen Catwalk durch den Raum.',
    'Beschreibe eine Person in der Runde wie eine Produktbeschreibung, ohne ihren Namen zu nennen.',
    'Halte eine 20-sekündige Dankesrede für einen völlig normalen Alltagsgegenstand.',
    'Sag das Alphabet so schnell du kannst, ohne einen Buchstaben auszulassen.',
    'Mach einen Handschlag mit der Person links von dir und gebt ihm einen Namen.',
    'Imitiere ein Emoji, bis die Gruppe es errät.',
    'Erzähle einen schlechten Witz mit maximaler Ernsthaftigkeit.',
    'Stell 15 Sekunden lang eine Statue dar. Wer dich zum Lachen bringt, gewinnt.',
    'Nenne drei Dinge, die du auf eine einsame Insel mitnehmen würdest.',
    'Erfinde einen neuen Feiertag und erkläre in 20 Sekunden die Regeln.',
    'Mach eine dramatische Wettervorhersage für den Raum, in dem ihr gerade seid.'
  ],

  person: [
    { name: 'Cristiano Ronaldo', aliases: ['CR7'], hints: ['Ich bin auf einer europäischen Insel geboren.', 'Ich wurde als Profisportler für meine enorme Sprungkraft bekannt.', 'Ich gewann mehrfach den Ballon d’Or.', 'Ich spielte unter anderem in England, Spanien und Italien.', 'Meine Rückennummer wurde zu einer weltweiten Marke.'] },
    { name: 'Lionel Messi', aliases: ['Leo Messi'], hints: ['Ich zog als Jugendlicher für meine Karriere nach Europa.', 'Ich bin für enge Ballführung und einen starken linken Fuß bekannt.', 'Den Großteil meiner Vereinskarriere verbrachte ich bei einem Club aus Katalonien.', '2022 gewann ich mit meiner Nationalmannschaft die Weltmeisterschaft.', 'Ich trug sehr lange die Nummer 10.'] },
    { name: 'Michael Jackson', aliases: ['MJ'], hints: ['Ich stand schon als Kind professionell auf der Bühne.', 'Ein einzelner weißer Handschuh wurde zu einem meiner Markenzeichen.', 'Ein rückwärts wirkender Tanzschritt ist eng mit mir verbunden.', 'Mein Album Thriller wurde eines der erfolgreichsten Alben überhaupt.', 'Ich wurde als King of Pop bezeichnet.'] },
    { name: 'Taylor Swift', aliases: [], hints: ['Meine Karriere begann stark im Country-Bereich.', 'Ich schreibe viele Songs über persönliche Erlebnisse.', 'Ich veröffentlichte mehrere meiner älteren Alben neu.', 'Eine meiner großen Tourneen trug den Namen verschiedener musikalischer Epochen.', 'Meine Fans nennen sich oft Swifties.'] },
    { name: 'Elon Musk', aliases: [], hints: ['Ich wurde in Südafrika geboren.', 'Ich war an einem frühen Online-Bezahldienst beteiligt.', 'Ich leite Unternehmen aus der Raumfahrt- und Elektroautobranche.', 'Ich kaufte eine große Social-Media-Plattform und benannte sie später um.', 'Raketen und Elektroautos gehören zu meinen bekanntesten Projekten.'] },
    { name: 'Albert Einstein', aliases: [], hints: ['Ich wurde im 19. Jahrhundert in Deutschland geboren.', 'Meine Arbeit veränderte das Verständnis von Raum und Zeit.', 'Ich erhielt den Nobelpreis für Physik.', 'Eine sehr kurze Formel machte mich weltberühmt.', 'Mein Name gilt bis heute als Synonym für ein Genie.'] },
    { name: 'Barack Obama', aliases: [], hints: ['Ich wurde auf Hawaii geboren.', 'Vor meiner höchsten politischen Position war ich Senator.', 'Ich erhielt während meiner Amtszeit den Friedensnobelpreis.', 'Ich war der 44. Präsident der USA.', 'Mein Wahlkampfslogan enthielt die Worte Yes We Can.'] },
    { name: 'Dwayne Johnson', aliases: ['The Rock'], hints: ['Ich spielte in meiner Jugend American Football.', 'Berühmt wurde ich zunächst in einem Ring.', 'Später wechselte ich erfolgreich ins Kino.', 'Meine Augenbraue wurde fast zu einem eigenen Markenzeichen.', 'Ein Spitzname von mir bezieht sich auf einen Felsen.'] },
    { name: 'Adele Adkins', aliases: ['Adele'], hints: ['Ich komme aus London.', 'Mehrere meiner Alben tragen Zahlen als Titel.', 'Meine Stimme ist für große Balladen bekannt.', 'Hello gehört zu meinen bekanntesten Songs.', 'Mein Künstlername besteht nur aus meinem Vornamen.'] },
    { name: 'Eminem Mathers', aliases: ['Eminem', 'Slim Shady', 'Marshall Mathers'], hints: ['Ich wuchs im Raum Detroit auf.', 'Ich wurde durch extrem schnelle Rap-Passagen bekannt.', 'Ein Film über einen jungen Rapper weist deutliche Parallelen zu meinem Leben auf.', 'Lose Yourself gewann einen Oscar.', 'Eine meiner Bühnenfiguren hat blondierte Haare und einen eigenen Namen.'] },
    { name: 'LeBron James', aliases: ['King James'], hints: ['Ich kam direkt aus der Highschool in eine große Profiliga.', 'Meine Heimatregion in Ohio spielt eine wichtige Rolle in meiner Karriere.', 'Ich gewann Meisterschaften mit Teams aus drei verschiedenen Städten.', 'Ich bin für Kraft, Spielübersicht und Langlebigkeit bekannt.', 'Mein Spitzname enthält einen königlichen Titel.'] },
    { name: 'Usain Bolt', aliases: [], hints: ['Ich komme aus der Karibik.', 'Meine Disziplinen dauerten meist nur wenige Sekunden.', 'Nach Siegen zeigte ich häufig eine auffällige Blitz-Pose.', 'Ich stellte Weltrekorde über 100 und 200 Meter auf.', 'Mein Nachname passt zufällig perfekt zu meiner Geschwindigkeit.'] },
    { name: 'Serena Williams', aliases: [], hints: ['Ich spielte eine Sportart mit Schläger und Netz.', 'Meine Schwester war ebenfalls Weltklasse in derselben Sportart.', 'Ich gewann zahlreiche Grand-Slam-Titel.', 'Kraftvolle Aufschläge waren eine meiner großen Stärken.', 'Ich prägte den Frauentennissport über viele Jahre.'] },
    { name: 'Keanu Reeves', aliases: [], hints: ['Ich wurde im Nahen Osten geboren und wuchs unter anderem in Kanada auf.', 'Ich spielte einen Hacker, der an seiner Realität zweifelt.', 'Später wurde ich als wortkarger Auftragskiller im Kino berühmt.', 'Ich gelte in Interviews oft als auffallend bescheiden.', 'Eine meiner Filmreihen heißt John Wick.'] },
    { name: 'Tom Hanks', aliases: [], hints: ['Ich spielte einen Mann, der jahrelang durch die US-Geschichte stolpert.', 'In einem anderen Film war mein engster Begleiter zeitweise ein Volleyball.', 'Ich sprach im Original einen Cowboy in einem Animationsfilm.', 'Ich gewann zweimal hintereinander den Oscar als bester Hauptdarsteller.', 'Forrest Gump gehört zu meinen bekanntesten Rollen.'] },
    { name: 'Rihanna Fenty', aliases: ['Rihanna'], hints: ['Ich komme aus Barbados.', 'Meine Karriere begann vor allem mit Musik.', 'Später baute ich erfolgreiche Marken in Beauty und Mode auf.', 'Umbrella gehört zu meinen größten Hits.', 'Mein Künstlername besteht aus meinem zweiten Vornamen.'] },
    { name: 'Ed Sheeran', aliases: [], hints: ['Ich bin ein britischer Singer-Songwriter.', 'Eine kleine Gitarre und eine Loop-Station begleiteten viele frühe Auftritte.', 'Meine Albumtitel bestehen häufig aus mathematischen Symbolen.', 'Shape of You wurde ein weltweiter Hit.', 'Rote Haare sind eines meiner auffälligsten Merkmale.'] },
    { name: 'Lady Gaga', aliases: ['Stefani Germanotta'], hints: ['Ich wurde in New York geboren.', 'Meine Bühnenoutfits sorgen regelmäßig für Schlagzeilen.', 'Ich spielte später auch große dramatische Filmrollen.', 'Poker Face gehört zu meinen frühen Welthits.', 'Mein Künstlername klingt nach einem aristokratischen Titel.'] },
    { name: 'Johnny Depp', aliases: [], hints: ['Ich spielte viele exzentrische Figuren.', 'Eine meiner bekanntesten Rollen trägt Kajal und Piratenkleidung.', 'Ich arbeitete mehrfach mit demselben Regisseur an düsteren Fantasiefilmen.', 'Eine Figur von mir besitzt Scheren statt normaler Hände.', 'Captain Jack Sparrow machte mich weltweit noch bekannter.'] },
    { name: 'Arnold Schwarzenegger', aliases: ['Arnie'], hints: ['Ich wurde in Österreich geboren.', 'Bevor ich Filmstar wurde, gewann ich große Bodybuilding-Titel.', 'Eine meiner Figuren kommt aus der Zukunft zurück.', 'Später wurde ich Gouverneur eines US-Bundesstaates.', 'I’ll be back ist eng mit einer meiner Rollen verbunden.'] },
    { name: 'Snoop Dogg', aliases: ['Snoop'], hints: ['Ich komme aus Kalifornien.', 'Meine Karriere begann im Westcoast-Rap.', 'Meine sehr entspannte Sprechweise ist sofort erkennbar.', 'Ich arbeitete häufig mit einem berühmten Produzenten und Rapper aus Compton zusammen.', 'Mein Künstlername enthält die Bezeichnung für einen Hund.'] },
    { name: 'Bill Gates', aliases: [], hints: ['Ich gründete als junger Mann ein Softwareunternehmen mit.', 'Ein Betriebssystem machte meine Firma weltweit dominant.', 'Ich war lange einer der reichsten Menschen der Welt.', 'Später widmete ich viel Zeit einer großen Stiftung.', 'Windows ist eng mit meiner Karriere verbunden.'] },
    { name: 'Steve Jobs', aliases: [], hints: ['Ich gründete in Kalifornien ein Technologieunternehmen mit.', 'Eine Garage spielt in der Ursprungsgeschichte meiner Firma eine große Rolle.', 'Ich präsentierte Produkte gern auf einer fast leeren Bühne.', 'Ein Smartphone veränderte unter meiner Führung den Markt nachhaltig.', 'Schwarzer Rollkragenpullover und Jeans wurden zu meinem typischen Look.'] },
    { name: 'Gordon Ramsay', aliases: [], hints: ['Ich wollte ursprünglich Profifußballer werden.', 'Berühmt wurde ich in professionellen Küchen und später im Fernsehen.', 'Ich bin für direkte und oft sehr laute Kritik bekannt.', 'Mehrere meiner Restaurants wurden mit Michelin-Sternen ausgezeichnet.', 'Hell’s Kitchen gehört zu meinen bekanntesten TV-Formaten.'] }
  ],

  mehrheit: [
    { q: 'Was ist der beste Mitternachtssnack?', o: ['Pizza', 'Döner', 'Pommes', 'Süßes'] },
    { q: 'Was rettet einen schlechten Tag am ehesten?', o: ['Schlaf', 'Essen', 'Sport', 'Freunde'] },
    { q: 'Welche App würdet ihr am schwersten löschen?', o: ['Instagram', 'TikTok', 'WhatsApp', 'YouTube'] },
    { q: 'Was ist im Urlaub wichtiger?', o: ['Essen', 'Wetter', 'Unterkunft', 'Aktivitäten'] },
    { q: 'Was ist die beste Tageszeit?', o: ['Morgen', 'Mittag', 'Abend', 'Nacht'] },
    { q: 'Was ist auf einer Party am wichtigsten?', o: ['Musik', 'Leute', 'Getränke', 'Location'] },
    { q: 'Welches Fast Food gewinnt?', o: ['Burger', 'Pizza', 'Döner', 'Tacos'] },
    { q: 'Was wäre als Superkraft am nützlichsten?', o: ['Fliegen', 'Unsichtbarkeit', 'Teleportation', 'Gedanken lesen'] },
    { q: 'Was ist nerviger?', o: ['Stau', 'Warteschlange', 'langsames WLAN', 'leerer Akku'] },
    { q: 'Was ist die beste Art zu reisen?', o: ['Auto', 'Zug', 'Flugzeug', 'Wohnmobil'] },
    { q: 'Welches Frühstück gewinnt?', o: ['Süß', 'Herzhaft', 'Nur Kaffee', 'Gar keins'] },
    { q: 'Was ist die bessere Freizeitaktivität?', o: ['Sport', 'Gaming', 'Serien', 'Ausgehen'] },
    { q: 'Was ist schlimmer zu vergessen?', o: ['Handy', 'Geldbeutel', 'Schlüssel', 'Kopfhörer'] },
    { q: 'Welches Wetter ist am besten?', o: ['Sonne', 'Regen', 'Schnee', 'Gewitter'] },
    { q: 'Was ist die beste Musik im Auto?', o: ['Rap', 'Pop', 'Rock', '90er/2000er'] },
    { q: 'Was ist im Kino unverzichtbar?', o: ['Popcorn', 'Nachos', 'Getränk', 'Nichts'] },
    { q: 'Was ist die bessere spontane Idee?', o: ['Roadtrip', 'Club', 'Spieleabend', 'Nachtessen'] },
    { q: 'Was ist die beste Saison?', o: ['Frühling', 'Sommer', 'Herbst', 'Winter'] },
    { q: 'Was wäre schlimmer für eine Woche?', o: ['Kein Internet', 'Kein Kaffee', 'Kein Auto', 'Kein Streaming'] },
    { q: 'Was ist das beste Haustier?', o: ['Hund', 'Katze', 'Fisch', 'Keins'] },
    { q: 'Was ist die beste Beilage?', o: ['Pommes', 'Reis', 'Kartoffeln', 'Salat'] },
    { q: 'Was ist die bessere Uhrzeit für Sport?', o: ['Früh', 'Mittags', 'Abends', 'Nie'] },
    { q: 'Was ist auf Reisen am nervigsten?', o: ['Packen', 'Warten', 'Umsteigen', 'Auspacken'] },
    { q: 'Was ist der beste Plan für einen freien Sonntag?', o: ['Ausschlafen', 'Ausflug', 'Sport', 'Gar nichts'] }
  ],

  skala: [
    'Wie spontan bist du? 1 = gar nicht, 10 = sofort Koffer packen.',
    'Wie ordentlich bist du? 1 = Chaos, 10 = alles hat seinen Platz.',
    'Wie ehrgeizig bist du bei Spielen? 1 = egal, 10 = Finale der Weltmeisterschaft.',
    'Wie gut kannst du kochen? 1 = Wasser brennt, 10 = Sternekoch.',
    'Wie früh bist du normalerweise bei Terminen? 1 = immer zu spät, 10 = viel zu früh.',
    'Wie gut kennst du dich mit Technik aus? 1 = Stecker suchen, 10 = Support-Hotline.',
    'Wie wahrscheinlich würdest du Karaoke machen? 1 = niemals, 10 = Mikro her.',
    'Wie sehr brauchst du morgens Kaffee oder Energy? 1 = gar nicht, 10 = lebensnotwendig.',
    'Wie leicht lässt du dich zu einer Wette überreden? 1 = unmöglich, 10 = sag nur worum.',
    'Wie gut kannst du Geheimnisse behalten? 1 = sofort erzählt, 10 = Tresor.',
    'Wie sportlich fühlst du dich heute? 1 = Sofa, 10 = Olympia.',
    'Wie gut ist dein Orientierungssinn? 1 = verlaufe mich zuhause, 10 = menschliches Navi.',
    'Wie geduldig bist du? 1 = null, 10 = Zen-Meister.',
    'Wie sehr planst du Reisen im Voraus? 1 = gar nicht, 10 = Excel-Tabelle.',
    'Wie wahrscheinlich gehst du heute als Letzte*r schlafen? 1 = unmöglich, 10 = sicher.',
    'Wie gut kannst du verlieren? 1 = gar nicht, 10 = fairer geht es nicht.',
    'Wie mutig bist du bei Achterbahnen? 1 = Kinderkarussell reicht, 10 = je höher desto besser.',
    'Wie oft singst du im Auto mit? 1 = nie, 10 = jedes Lied.',
    'Wie gut kannst du Smalltalk? 1 = Fluchtreflex, 10 = rede mit jedem.',
    'Wie wahrscheinlich würdest du spontan die Haare verändern? 1 = niemals, 10 = heute noch.',
    'Wie wichtig ist dir gutes Essen im Urlaub? 1 = egal, 10 = Hauptgrund der Reise.',
    'Wie schnell antwortest du normalerweise auf Nachrichten? 1 = Tage später, 10 = sofort.',
    'Wie sehr liebst du Überraschungen? 1 = bitte nicht, 10 = immer her damit.',
    'Wie wahrscheinlich würdest du bei einer Gameshow mitmachen? 1 = nie, 10 = wo anmelden?'
  ]
};
