'use strict';

// SüffIQ: Party-/Club-/Festival-/Rap-Banger. Keine Balladen-Rotation.
// Feste YouTube-IDs = kein YouTube-Data-API-Key nötig.
// `start` setzt einen markanten Einstieg; ab dort läuft der Song am Stück.
module.exports = [
  // EDM / Festival / David Guetta
  { title: 'We Are The People', artist: 'Empire Of The Sun', videoId: 'a47Y1lCRHlM', start: 41, aliases: ['We Are the People'] },
  { title: 'Memories', artist: 'David Guetta feat. Kid Cudi', videoId: 'NUVCQXMUVnI', start: 38 },
  { title: 'Titanium', artist: 'David Guetta feat. Sia', videoId: 'JRfuAukYTKg', start: 45 },
  { title: 'Sexy Bitch', artist: 'David Guetta feat. Akon', videoId: 'mIIN_SGQy9c', start: 30, aliases: ['Sexy Chick'] },
  { title: 'Where Them Girls At', artist: 'David Guetta feat. Flo Rida & Nicki Minaj', videoId: 'p4kVWCSzfK4', start: 34 },
  { title: 'Play Hard', artist: 'David Guetta feat. Ne-Yo & Akon', videoId: '5dbEhBKGOtY', start: 31 },
  { title: 'Hey Mama', artist: 'David Guetta feat. Nicki Minaj, Bebe Rexha & Afrojack', videoId: 'uO59tfQ2TbA', start: 39 },
  { title: 'Levels', artist: 'Avicii', videoId: '_ovdm2yX4MA', start: 18 },
  { title: 'Wake Me Up', artist: 'Avicii', videoId: 'IcrbM1l_BoI', start: 43 },
  { title: 'The Nights', artist: 'Avicii', videoId: 'UtF6Jej8yb4', start: 37 },
  { title: 'Animals', artist: 'Martin Garrix', videoId: 'gCYcHz2k5x0', start: 47 },
  { title: "Don't You Worry Child", artist: 'Swedish House Mafia', videoId: '1y6smkh6c-0', start: 52, aliases: ['Dont You Worry Child'] },
  { title: 'Save The World', artist: 'Swedish House Mafia', videoId: 'BXpdmKELE1k', start: 46, aliases: ['Save the World'] },
  { title: 'Summer', artist: 'Calvin Harris', videoId: 'ebXbLfLACGM', start: 35 },
  { title: 'Feel So Close', artist: 'Calvin Harris', videoId: 'dGghkjpNCQ8', start: 40 },
  { title: 'This Is What You Came For', artist: 'Calvin Harris feat. Rihanna', videoId: 'kOkQ4T5WO9E', start: 44 },
  { title: 'One Kiss', artist: 'Calvin Harris & Dua Lipa', videoId: 'DkeiKbqa02g', start: 43 },
  { title: 'We Found Love', artist: 'Rihanna feat. Calvin Harris', videoId: 'tg00YEETFzg', start: 48 },
  { title: 'Turn Down for What', artist: 'DJ Snake & Lil Jon', videoId: 'HMUDVMiITOU', start: 20, aliases: ['Turn Down For What'] },
  { title: 'Lean On', artist: 'Major Lazer & DJ Snake feat. MØ', videoId: 'YqeW9_5kURI', start: 35 },
  { title: 'Let Me Love You', artist: 'DJ Snake feat. Justin Bieber', videoId: 'euCqAq6BRa4', start: 41 },
  { title: 'Taki Taki', artist: 'DJ Snake feat. Selena Gomez, Ozuna & Cardi B', videoId: 'ixkoVwKQaJg', start: 39 },
  { title: 'Faded', artist: 'Alan Walker', videoId: '60ItHLz5WEA', start: 36 },
  { title: 'Clarity', artist: 'Zedd feat. Foxes', videoId: 'IxxstCcJlsc', start: 43 },
  { title: 'Rather Be', artist: 'Clean Bandit feat. Jess Glynne', videoId: 'm-M1AtrxztU', start: 42 },
  { title: 'Get Lucky', artist: 'Daft Punk feat. Pharrell Williams', videoId: '5NV6Rdv1a3I', start: 30 },

  // 2000er / 2010er Clubhits
  { title: 'I Gotta Feeling', artist: 'The Black Eyed Peas', videoId: 'uSD4vsh1zDA', start: 42 },
  { title: 'Pump It', artist: 'The Black Eyed Peas', videoId: 'ZaI2IlHwmgQ', start: 31 },
  { title: 'Boom Boom Pow', artist: 'The Black Eyed Peas', videoId: '4m48GqaOz90', start: 39 },
  { title: 'Party Rock Anthem', artist: 'LMFAO', videoId: 'KQ6zr6kCPj8', start: 46 },
  { title: 'Sexy and I Know It', artist: 'LMFAO', videoId: 'wyx6JDQCslE', start: 38 },
  { title: 'Timber', artist: 'Pitbull feat. Kesha', videoId: 'hHUbLv4ThOo', start: 38 },
  { title: 'Yeah!', artist: 'Usher feat. Lil Jon & Ludacris', videoId: 'GxBSyx85Kp8', start: 29, aliases: ['Yeah'] },
  { title: "DJ Got Us Fallin' in Love", artist: 'Usher feat. Pitbull', videoId: 'C-dvTjK_07c', start: 37, aliases: ['DJ Got Us Falling in Love'] },
  { title: 'Low', artist: 'Flo Rida feat. T-Pain', videoId: 'U2waT9TxPU0', start: 27 },
  { title: 'Good Feeling', artist: 'Flo Rida', videoId: '3OnnDqH6Wj8', start: 36 },
  { title: "Club Can't Handle Me", artist: 'Flo Rida feat. David Guetta', videoId: 'SgM3r8xKfGE', start: 41, aliases: ['Club Cant Handle Me'] },
  { title: 'Temperature', artist: 'Sean Paul', videoId: 'dW2MmuA1nI4', start: 35 },
  { title: 'Get Busy', artist: 'Sean Paul', videoId: 'oPQ3o14ksaM', start: 34 },
  { title: 'Hips Don\'t Lie', artist: 'Shakira feat. Wyclef Jean', videoId: 'DUT5rEU6pqM', start: 43, aliases: ['Hips Dont Lie'] },
  { title: 'Waka Waka', artist: 'Shakira', videoId: 'pRpeEdMmmQ0', start: 47, aliases: ['Waka Waka This Time for Africa'] },
  { title: 'On The Floor', artist: 'Jennifer Lopez feat. Pitbull', videoId: 't4H_Zoh7G5A', start: 42, aliases: ['On the Floor'] },
  { title: 'Tik Tok', artist: 'Kesha', videoId: 'iP6XpLQM2Cs', start: 38, aliases: ['TiK ToK'] },
  { title: 'Poker Face', artist: 'Lady Gaga', videoId: 'bESGLojNYSo', start: 44 },
  { title: 'Just Dance', artist: 'Lady Gaga feat. Colby O\'Donis', videoId: '2Abk1jAONjw', start: 39 },
  { title: 'Bad Romance', artist: 'Lady Gaga', videoId: 'qrO4YZeyl0I', start: 52 },
  { title: 'Toxic', artist: 'Britney Spears', videoId: 'LOZuxwVk7TU', start: 48 },
  { title: 'Umbrella', artist: 'Rihanna feat. Jay-Z', videoId: 'CvBfHwUxHIk', start: 48 },
  { title: 'Only Girl (In The World)', artist: 'Rihanna', videoId: 'pa14VNsdSYM', start: 43, aliases: ['Only Girl'] },
  { title: "Don't Stop The Music", artist: 'Rihanna', videoId: 'yd8jh9QYfEs', start: 45, aliases: ['Dont Stop the Music'] },
  { title: 'Firework', artist: 'Katy Perry', videoId: 'QGJuMBdaqIw', start: 46 },
  { title: 'California Gurls', artist: 'Katy Perry feat. Snoop Dogg', videoId: 'F57P9C4SAW4', start: 42 },
  { title: 'Shake It Off', artist: 'Taylor Swift', videoId: 'nfWlot6h_JM', start: 42 },
  { title: 'Dynamite', artist: 'Taio Cruz', videoId: 'Vysgv7qVYTo', start: 39 },
  { title: 'Uptown Funk', artist: 'Mark Ronson feat. Bruno Mars', videoId: 'OPf0YbXqDm0', start: 30 },
  { title: '24K Magic', artist: 'Bruno Mars', videoId: 'UqyT8IEBkvY', start: 34 },
  { title: 'Moves Like Jagger', artist: 'Maroon 5 feat. Christina Aguilera', videoId: 'iEPTlhBmwRg', start: 41 },
  { title: 'Scream & Shout', artist: 'will.i.am feat. Britney Spears', videoId: 'kYtGl1dX5qI', start: 39, aliases: ['Scream and Shout'] },
  { title: 'Work from Home', artist: 'Fifth Harmony feat. Ty Dolla $ign', videoId: '5GL9JoH4Sws', start: 40 },
  { title: 'Havana', artist: 'Camila Cabello feat. Young Thug', videoId: 'BQ0mxQXmLsk', start: 51 },
  { title: 'Mi Gente', artist: 'J Balvin & Willy William', videoId: 'wnJ6LuUFpMo', start: 38 },
  { title: 'Danza Kuduro', artist: 'Don Omar feat. Lucenzo', videoId: '7zp1TbLFPp8', start: 34 },
  { title: 'Gangnam Style', artist: 'PSY', videoId: '9bZkp7q19f0', start: 42 },
  { title: 'Despacito', artist: 'Luis Fonsi feat. Daddy Yankee', videoId: 'kJQP7kiw5Fk', start: 51 },
  { title: 'Blinding Lights', artist: 'The Weeknd', videoId: '4NRXx6U8ABQ', start: 21 },

  // Rap / Hip-Hop / Deutschrap
  { title: 'In Da Club', artist: '50 Cent', videoId: '5qm8PH4xAss', start: 18, aliases: ['In The Club'] },
  { title: 'Candy Shop', artist: '50 Cent feat. Olivia', videoId: 'SRcnnId15BA', start: 36 },
  { title: "Can't Hold Us", artist: 'Macklemore & Ryan Lewis feat. Ray Dalton', videoId: '2zNSgSzhBfM', start: 54, aliases: ['Cant Hold Us'] },
  { title: 'Thrift Shop', artist: 'Macklemore & Ryan Lewis feat. Wanz', videoId: 'QK8mJJJvaes', start: 32 },
  { title: 'Lose Yourself', artist: 'Eminem', videoId: '_Yhyp-_hX2s', start: 24 },
  { title: 'Without Me', artist: 'Eminem', videoId: 'YVkUvmDQ3HY', start: 36 },
  { title: 'Still D.R.E.', artist: 'Dr. Dre feat. Snoop Dogg', videoId: 'QZXc39hT8t4', start: 25, aliases: ['Still DRE'] },
  { title: "Drop It Like It's Hot", artist: 'Snoop Dogg feat. Pharrell', videoId: 'GtUVQei3nX4', start: 34 },
  { title: 'Stronger', artist: 'Kanye West', videoId: 'PsO6ZnUZI0g', start: 43 },
  { title: 'SICKO MODE', artist: 'Travis Scott', videoId: '6ONRf7h3Mdk', start: 45, aliases: ['Sicko Mode'] },
  { title: "God's Plan", artist: 'Drake', videoId: 'xpVfcZ0ZcFM', start: 41, aliases: ['Gods Plan'] },
  { title: 'Congratulations', artist: 'Post Malone feat. Quavo', videoId: 'SC4xMk98Pdc', start: 40 },
  { title: 'Roller', artist: 'Apache 207', videoId: 'Fo3DAhiNKQo', start: 30 },
  { title: 'Alles Neu', artist: 'Peter Fox', videoId: 'qdtLCfEcPL4', start: 35 },
  { title: 'Augenbling', artist: 'Seeed', videoId: 'qttGJ3il62Y', start: 38 },
  { title: 'Leider Geil', artist: 'Deichkind', videoId: 'ZPJlyRv_IGI', start: 39 },

  // Mitsing-/Rock-/Retro-Banger
  { title: 'The Final Countdown', artist: 'Europe', videoId: '9jK-NcRmVcw', start: 22, aliases: ['Final Countdown'] },
  { title: 'Thunderstruck', artist: 'AC/DC', videoId: 'v2AC41dglnM', start: 25 },
  { title: "Livin' on a Prayer", artist: 'Bon Jovi', videoId: 'lDK9QqIzhwk', start: 47, aliases: ['Living on a Prayer'] },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", videoId: '1w7OgIMMRc4', start: 58, aliases: ['Sweet Child of Mine'] },
  { title: 'Take On Me', artist: 'a-ha', videoId: 'djV11Xbc914', start: 45 },
  { title: 'Dancing Queen', artist: 'ABBA', videoId: 'xFrGuyw1V8s', start: 45 },
  { title: 'Rasputin', artist: 'Boney M.', videoId: '16y1AkoZkmQ', start: 37 },
  { title: 'September', artist: 'Earth, Wind & Fire', videoId: 'Gs069dndIYk', start: 42 },
  { title: 'Y.M.C.A.', artist: 'Village People', videoId: 'CS9OO0S5w2k', start: 45, aliases: ['YMCA'] },
  { title: "Stayin' Alive", artist: 'Bee Gees', videoId: 'fNFzfwLM72c', start: 39, aliases: ['Staying Alive'] },
  { title: 'Mr. Brightside', artist: 'The Killers', videoId: 'gGdGFtwCNBE', start: 43, aliases: ['Mr Brightside'] },
  { title: 'Sex on Fire', artist: 'Kings of Leon', videoId: 'RF0HhrwIwp0', start: 38 },
  { title: 'Seven Nation Army', artist: 'The White Stripes', videoId: '0J2QdDbelmY', start: 31 },
  { title: 'All the Small Things', artist: 'Blink-182', videoId: '9Ht5RZpzPqw', start: 40 },
  { title: 'In the End', artist: 'Linkin Park', videoId: 'eVTXPUF4Oz4', start: 37 },
  { title: 'Numb', artist: 'Linkin Park', videoId: 'kXYiU_JCYtU', start: 39 },
  { title: 'Chop Suey!', artist: 'System Of A Down', videoId: 'CSvFpBOe8eY', start: 36, aliases: ['Chop Suey'] },
  { title: 'Last Resort', artist: 'Papa Roach', videoId: 'j0lSpNtjPM8', start: 37 },
  { title: 'Bring Me to Life', artist: 'Evanescence', videoId: '3YxaaGgTQYM', start: 45 },
  { title: "Don't Stop Me Now", artist: 'Queen', videoId: 'HgzGwKwLmgM', start: 40, aliases: ['Dont Stop Me Now'] },
  { title: 'Eye of the Tiger', artist: 'Survivor', videoId: 'btPJPFnesV4', start: 46 },
  { title: 'Du hast', artist: 'Rammstein', videoId: 'W3q8Od5qJio', start: 43, aliases: ['Du Hast'] }
];
